#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the code points str.isdigit and str.isnumeric accept beyond Nd.

Python's three numeric predicates are three different sets, and only the
narrowest is a Unicode general category:

    isdecimal()  Nd exactly                     -- unicode.Nd in Go
    isdigit()    Nd plus Numeric_Type=Digit     -- 128 more, e.g. SUPERSCRIPT TWO
    isnumeric()  anything with a numeric value  -- 81 more still, including CJK
                                                   ideographs like U+4E00 (Lo)

Reading isdigit as Nd is the easy mistake -- `"²".isdigit()` is True in
Python and was False here, and isalnum inherited it. The two corrections are
small and they are not a list to curate by hand, so they come from the same
CPython this project grades against.

The tables here used to be *corrections to Go's own*: isdecimal was
unicode.IsDigit, and isnumeric added unicode.Nl and unicode.No to it. That is
sound only while Go and CPython agree on those categories, which nothing
checked and which is not true -- Go is on Unicode 15.0.0 and CPython 3.11 on
14.0.0, so Go has twenty decimal digits (Kawi, Nag Mundari) and twenty No
characters (Kaktovik numerals) that the specification does not. All three
predicates answered True for all forty.

So Nl and No are written out in full here too, and the decimal half comes from
value/decimaltable.go, which int() and float() already read. One table, one
Unicode version, five callers.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "strclass.go"
MAX = 0x110000


def ranges(points: list[int]) -> list[tuple[int, int]]:
    """Collapse sorted code points into inclusive ranges."""
    out: list[tuple[int, int]] = []
    for cp in points:
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def table(name: str, points: list[int], doc: str) -> str:
    r16 = [r for r in ranges(points) if r[1] <= 0xFFFF]
    r32 = [r for r in ranges(points) if r[1] > 0xFFFF]
    lines = [doc, "var %s = &unicode.RangeTable{" % name]
    if r16:
        lines.append("\tR16: []unicode.Range16{")
        for lo, hi in r16:
            lines.append("\t\t{0x%04x, 0x%04x, 1}," % (lo, hi))
        lines.append("\t},")
    if r32:
        lines.append("\tR32: []unicode.Range32{")
        for lo, hi in r32:
            lines.append("\t\t{0x%06x, 0x%06x, 1}," % (lo, hi))
        lines.append("\t},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    nd = {cp for cp in range(MAX) if unicodedata.category(chr(cp)) == "Nd"}
    nl_no = {cp for cp in range(MAX)
             if unicodedata.category(chr(cp)) in ("Nl", "No")}
    digit = {cp for cp in range(MAX) if chr(cp).isdigit()}
    numeric = {cp for cp in range(MAX) if chr(cp).isnumeric()}

    # Nd is a subset of both, and Nl/No of isnumeric; only the remainder is
    # written out. Assert it rather than assume it -- a future Unicode revision
    # that broke this would otherwise silently narrow the predicates.
    assert nd <= digit and nd <= numeric, "Nd is no longer a subset"
    assert nl_no <= numeric, "Nl/No is no longer a subset of isnumeric"

    digit_extra = sorted(digit - nd)
    numeric_extra = sorted(numeric - nd - nl_no)
    nl_no_all = sorted(nl_no)

    header = f'''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_strclass.py from CPython {sys.version.split()[0]}. DO NOT EDIT.
//
// What str.isdigit and str.isnumeric accept beyond the decimal digits.
// See the generator for why each predicate is a different set, and why none of
// them reads Go's own category tables.

package gojja2

import "unicode"
'''
    body = "\n\n".join([
        header,
        table("digitExtra", digit_extra,
              "// digitExtra is Numeric_Type=Digit outside Nd: the superscripts and\n"
              "// the parenthesised and circled digits that isdigit accepts and\n"
              "// isdecimal does not."),
        table("nlNo", nl_no_all,
              "// nlNo is CPython's Nl and No categories in full -- the letter numerals\n"
              "// such as ROMAN NUMERAL FIVE and the other numerals such as VULGAR\n"
              "// FRACTION ONE HALF.\n"
              "//\n"
              "// In full, and not as a correction to unicode.Nl and unicode.No, because\n"
              "// Go carries a later Unicode than the CPython this is graded against: its\n"
              "// No has the twenty Kaktovik numerals that CPython 3.11 does not, and\n"
              "// isnumeric answered True for all twenty."),
        table("numericExtra", numeric_extra,
              "// numericExtra is everything carrying a numeric value that is neither\n"
              "// Nd nor Nl/No -- almost all of it CJK ideographs such as U+4E00, which\n"
              "// isnumeric accepts and isdigit does not."),
    ])
    DST.write_text(body + "\n", encoding="utf-8")
    print(f"wrote {len(digit_extra)} digit, {len(numeric_extra)} numeric and "
          f"{len(nl_no_all)} Nl/No code points into {DST.relative_to(ROOT)}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
