#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the filter and test signatures gojja2 checks calls against.

Every argument error a template can provoke is CPython's, raised by CPython's
own argument binding against the signature of a function in jinja2.filters or
jinja2.tests. Transcribing 48 signatures by hand is exactly the kind of work
that is done once, drifts, and is never checked again -- so they are read out
of the pinned jinja2 with inspect.signature instead.

The counts here are Python's, so the messages can be too: a filter called with
too many arguments reports the numbers CPython would, injected first parameter
included, because that is what the template author sees on the other
implementation.
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

import jinja2
from jinja2.filters import FILTERS
from jinja2.tests import TESTS
from jinja2.utils import pass_eval_context  # noqa: F401  (import proves the API shape)

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "arity.go"

HEADER = '''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_arity.py from jinja2 {version}. DO NOT EDIT.
//
// One entry per filter and test, carrying the signature CPython binds a call
// against. The counts are Python's, including the environment or context
// jinja2 injects as the first parameter, so that an arity error can report the
// numbers a template author would see on the other implementation.

package gojja2

// signature is a jinja2 filter or test as Python sees it.
type signature struct{{
	// pyName is the function CPython names in the error.
	pyName string
	// params are the parameters a template can reach, the filtered value
	// or tested value first. A keyword may name any of them -- including
	// the first, which is how `x|upper(s=1)` becomes "multiple values".
	params []string
	// injected counts the parameters jinja2 supplies itself: the
	// environment, the context, or the eval context.
	injected int
	// required is how many parameters have no default, injected included.
	required int
	// total is the parameter count, injected included; -1 for *args.
	total int
	// varKw accepts any keyword, which is what **kwargs means.
	varKw bool
	// builtin marks one of Python's own functions, which jinja2 registers
	// directly -- abs, len, callable, and the operator.* comparisons. A C
	// function words its argument errors differently from a Python one,
	// and differently from each other, so the wordings are probed out of
	// CPython rather than derived from the signature.
	builtin bool
	// countMessage is what this C function says for any wrong number of
	// positional arguments, too few or too many alike, with the count
	// given. Empty for a Python function, which words it from the
	// signature instead.
	countMessage string
	// kwMessage is what it says when handed a keyword argument at all. It
	// names neither the keyword nor the count.
	kwMessage string
}}

// filterSignatures and testSignatures are keyed by the name a template uses.
// They are separate maps because four names -- float, lower, string and upper
// -- are both a filter and a test, with different signatures.
var filterSignatures = map[string]signature{{
{filters}}}

var testSignatures = map[string]signature{{
{tests}}}
'''


# injectedNames are the parameters jinja2 fills in itself. Which of them a
# filter takes cannot be read from its jinja_pass_arg attribute: the
# @async_variant wrapper carries the attribute while the sync implementation
# underneath may not take the parameter at all -- do_list is decorated
# pass_eval_context and sync_do_list takes only the value, which is why CPython
# reports "sync_do_list() takes 1 positional argument". The signature of the
# function CPython actually binds is the only thing that answers this, so the
# wrapper is unwrapped first and the first parameter's *name* decides.
INJECTED_NAMES = {"environment", "env", "context", "eval_ctx"}


def probe(fn, *args, **kwargs) -> str | None:
    """Return the TypeError CPython raises for this call, if it raises one."""
    try:
        fn(*args, **kwargs)
    except TypeError as e:
        return str(e)
    except Exception:
        return None
    return None


def substitute(a: str, b: str, lo: int, hi: int, what: str) -> str:
    """Turn two messages differing only in a count into one %d format."""
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    j = 0
    while j < len(a) - i and j < len(b) - i and a[len(a) - 1 - j] == b[len(b) - 1 - j]:
        j += 1
    if a[i : len(a) - j] != str(lo) or b[i : len(b) - j] != str(hi):
        raise SystemExit(
            f"{what}: cannot read a count out of CPython's wording; got {a!r} and {b!r}"
        )
    return a[:i] + "%d" + a[len(a) - j :]


def builtin_messages(fn, total: int, what: str) -> tuple[str, str]:
    """Probe CPython for how this C function words its argument errors.

    There is more than one wording, and which one a function uses cannot be
    read off its signature: abs, len and callable say "abs() takes exactly one
    argument (2 given)", while operator.eq -- which jinja2 registers as the
    `eq`, `==` and `equalto` tests -- says "eq expected 2 arguments, got 3",
    and names itself "_operator.eq" when refusing a keyword. Guessing produced
    the first wording for all of them, so the real messages are taken from the
    real functions instead.

    The count template comes from diffing two wrong-count calls, so the shape
    is never assumed; anything that does not differ in exactly the count stops
    the generator.
    """
    if total < 0:
        raise SystemExit(f"{what}: a builtin taking *args is not handled")
    lo, hi = total + 1, total + 7
    too_many = substitute(
        probe(fn, *([None] * lo)), probe(fn, *([None] * hi)), lo, hi, what
    )
    # One too few has to reach the same wording, or a single template cannot
    # stand for both and the caller below would report the wrong thing.
    few = total - 1
    if few >= 0:
        got = probe(fn, *([None] * few))
        if got != too_many % few:
            raise SystemExit(
                f"{what}: too few and too many are worded differently: "
                f"{got!r} against {too_many % few!r}"
            )
    # The keyword refusal names neither the key nor the count, which two
    # different keys confirm rather than assume.
    first, second = probe(fn, **{"zz": None}), probe(fn, **{"qq": None})
    if first is None or first != second:
        raise SystemExit(
            f"{what}: keyword refusal is not a constant message: {first!r} and {second!r}"
        )
    return too_many, first


def go_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def describe(fn) -> dict | None:
    """Read one callable's signature, or None when it cannot be introspected."""
    target = inspect.unwrap(fn)
    try:
        sig = inspect.signature(target)
    except (TypeError, ValueError):
        return None

    ps = list(sig.parameters.values())
    passes = hasattr(fn, "jinja_pass_arg")
    injected = 1 if passes and ps and ps[0].name in INJECTED_NAMES else 0
    if passes and ps and ps[0].name not in INJECTED_NAMES | {"value"}:
        # A spelling this does not know about would silently shift every
        # count in the signature by one, so it stops here instead.
        raise SystemExit(
            f"{getattr(target, '__name__', '?')}: unrecognised injected parameter "
            f"{ps[0].name!r}; add it to INJECTED_NAMES or exclude it"
        )
    builtin = inspect.isbuiltin(target)
    params, required, total, var_kw = [], 0, 0, False
    for i, p in enumerate(ps):
        if p.kind is p.VAR_KEYWORD:
            var_kw = True
            continue
        if p.kind is p.VAR_POSITIONAL:
            total = -1
            continue
        total = total if total < 0 else total + 1
        if p.default is p.empty:
            required += 1
        if i >= injected:
            params.append(p.name)
    count_msg, kw_msg = "", ""
    if builtin:
        count_msg, kw_msg = builtin_messages(target, total, getattr(target, "__name__", "?"))
    return {
        "pyName": getattr(target, "__name__", "?"),
        "params": params,
        "injected": injected,
        "required": required,
        "total": total,
        "varKw": var_kw,
        "builtin": builtin,
        "countMessage": count_msg,
        "kwMessage": kw_msg,
    }


def rows_for(kind: str, table: dict) -> tuple[str, int]:
    rows = []
    for name in sorted(table):
        d = describe(table[name])
        if d is None:
            print(f"skipped {kind} {name}: not introspectable", file=sys.stderr)
            continue
        names = ", ".join(f'"{p}"' for p in d["params"])
        rows.append(
            f'\t"{name}": {{pyName: "{d["pyName"]}", '
            f"params: []string{{{names}}}, "
            f'injected: {d["injected"]}, required: {d["required"]}, '
            f'total: {d["total"]}, varKw: {str(d["varKw"]).lower()}, '
            f'builtin: {str(d["builtin"]).lower()}, '
            f'countMessage: {go_string(d["countMessage"])}, '
            f'kwMessage: {go_string(d["kwMessage"])}}},\n'
        )
    return "".join(rows), len(rows)


def main() -> int:
    filters, nf = rows_for("filter", FILTERS)
    tests, nt = rows_for("test", TESTS)
    DST.write_text(
        HEADER.format(version=jinja2.__version__, filters=filters, tests=tests),
        encoding="utf-8",
    )
    print(f"wrote {nf} filter and {nt} test signatures into {DST.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
