#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the built-in method signatures gojja2 checks calls against.

The filters and tests got this treatment first (see gen_arity.py); the methods
on str, list, dict and tuple never did, and every one of them accepted whatever
it was given. `[1].append("a", 1)` bound the extra argument to nothing and
answered None, where CPython says "list.append() takes exactly one argument (2
given)" -- and there are some seven hundred such calls across the shapes a
template can write.

The wordings cannot be derived from the signature. A method that takes nothing
says "str.upper() takes no arguments (1 given)"; one that takes exactly one says
"list.append() takes exactly one argument (2 given)"; one with an optional
second says "center() takes at least 1 argument (0 given)" one way and "at most
2 arguments (3 given)" the other; and the names in them are sometimes qualified
and sometimes not. So they are probed out of CPython, and anything whose shape
this cannot read stops the generator rather than being guessed at.
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

import jinja2

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "method_arity.go"
METHODS_GO = ROOT / "methods.go"
# bytes has forty-two methods and they live in a file of their own.
BYTES_GO = ROOT / "bytes_methods.go"

# A receiver of each type, chosen so that a correctly-shaped call is as likely
# as possible to *work*: the probe reads arity errors, and an argument error of
# some other kind is simply not one.
RECEIVERS = {
    "str": "aBc dEf",
    "list": [3, 1, 2],
    "dict": {"a": 1, "b": 2},
    "tuple": (3, 1, 2),
    "bytes": b"aBc dEf",
}

TYPES = {"str": str, "list": list, "dict": dict, "tuple": tuple, "bytes": bytes}

# A value that is wrong for almost every parameter, so a call that gets past
# the arity check fails for a reason that is visibly not about the count.
SENTINEL = object()

HEADER = '''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_methods.py from CPython {python}. DO NOT EDIT.
//
// One entry per built-in method a template can call, carrying what CPython
// accepts and what it says when it does not. The wordings are probed rather
// than derived: a method that takes nothing, one that takes exactly one, and
// one with an optional second all word it differently, and no rule connects
// the wording to the signature.

package gojja2

// methodSignature is a built-in method as CPython binds a call to it.
type methodSignature struct {{
	// minArgs and maxArgs bound the positional count, self excluded.
	// maxArgs is -1 when the method takes any number.
	minArgs, maxArgs int
	// fewMessage and manyMessage carry the offending count as %d. They are
	// the same string when CPython words both directions alike, and
	// fewMessage is empty when no call can be too short.
	fewMessage, manyMessage string
	// kwNames are the keyword arguments the method accepts, if any.
	kwNames []string
	// kwMessage is what it says when handed a keyword it does not take. It
	// carries the name as %s when CPython includes it, and nothing when it
	// does not.
	kwMessage string
	// anyKw marks a method that takes **kwargs, so no keyword is refused.
	anyKw bool
}}

// methodSignatures is keyed by "<type>.<method>", the type being the receiver's
// Python name.
var methodSignatures = map[string]methodSignature{{
{rows}}}
'''


def probe(fn, *args, **kwargs) -> tuple[str, str] | None:
    """Return (exception type, message) for this call, or None if it survived."""
    try:
        fn(*args, **kwargs)
    except Exception as e:  # noqa: BLE001 -- any failure is a data point
        return type(e).__name__, str(e)
    return None


def substitute(a: str, b: str, lo: int, hi: int, what: str) -> str:
    """Turn two messages differing only in a count into one %d format."""
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    j = 0
    while j < len(a) - i and j < len(b) - i and a[len(a) - 1 - j] == b[len(b) - 1 - j]:
        j += 1
    if a[i : len(a) - j] != str(lo) or b[i : len(b) - j] != str(hi):
        raise SystemExit(
            f"{what}: cannot read a count out of CPython's wording; got {a!r} and {b!r}"
        )
    return a[:i] + "%d" + a[len(a) - j :]


def is_arity_error(got, n: int) -> str | None:
    """The message, when this failure is about the *count* and not the values.

    CPython puts the count at the end of every arity message and nowhere else:
    "takes no arguments (3 given)", "expected at most 2 arguments, got 5". An
    error about an argument names a *position* -- "maketrans() argument 2 must
    be str" -- so the number alone does not settle it and the ending does.
    Every candidate found this way is then checked by diffing two of them, so a
    coincidence cannot survive either.
    """
    if got is None or got[0] != "TypeError":
        return None
    if not (got[1].endswith("got %d" % n) or got[1].endswith("(%d given)" % n)):
        return None
    return got[1]


def one_count_template(message: str, n: int, what: str) -> str:
    """Turn a single message into a %d template by replacing the count in it."""
    parts = re.split(r"(?<![0-9])(%d)(?![0-9])" % n, message)
    if len(parts) != 3:
        raise SystemExit(
            f"{what}: the count {n} appears {len(parts) // 2} times in {message!r}"
        )
    return parts[0] + "%d" + parts[2]


def text_signature_keywords(fn) -> list[str] | None:
    """The keyword-capable parameter names out of a builtin's __text_signature__.

    inspect refuses a handful of builtins whose signature text it cannot parse
    -- bytes.hex declares `sep=<unrepresentable>` -- and the names are right
    there in the text. There are exactly three across the types here, and two
    of them are positional-only, so the `/` marker has to be honoured or this
    would report keywords that CPython refuses.

    A method with no signature text at all declares no keywords: CPython says
    "takes no keyword arguments" for every one of them, which was checked.
    Returns None only when the text is there and cannot be read, which is the
    case that must stop the generator rather than be guessed at.
    """
    text = getattr(fn, "__text_signature__", None)
    if text is None:
        return []
    inner = text.strip()
    if not (inner.startswith("(") and inner.endswith(")")):
        return None

    fields: list[str] = []
    depth, field = 0, ""
    for ch in inner[1:-1] + ",":
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            fields.append(field.strip())
            field = ""
            continue
        field += ch

    # Everything up to a "/" is positional-only and cannot be named.
    if "/" in fields:
        fields = fields[fields.index("/") + 1:]
    names = []
    for f in fields:
        if not f or f in ("/", "*") or f.startswith("$") or f.startswith("*"):
            continue
        names.append(f.split("=", 1)[0].strip())
    return names


def keyword_rule(fn, lead, what: str) -> tuple[list[str], str, bool]:
    """The keywords a method accepts, and what it says about one it does not.

    The third result marks **kwargs, where nothing is refused at all.
    """
    names: list[str] = []
    try:
        sig = inspect.signature(fn)
        for p in sig.parameters.values():
            if p.kind in (p.KEYWORD_ONLY, p.POSITIONAL_OR_KEYWORD) and p.name != "self":
                names.append(p.name)
    except (TypeError, ValueError):
        # inspect refuses some builtins whose __text_signature__ it cannot
        # parse -- bytes.hex declares `sep=<unrepresentable>` -- and the
        # names are right there in the text. Recording "no keywords" here
        # is the guess this module exists not to make: bytes.hex takes two,
        # and the generated table said it took none.
        names = text_signature_keywords(fn)
        if names is None:
            raise SystemExit(f"{what}: cannot read the parameter names")

    try:
        sig = inspect.signature(fn)
        any_kw = any(p.kind is p.VAR_KEYWORD for p in sig.parameters.values())
    except (TypeError, ValueError):
        any_kw = False

    first = probe(fn, *lead, **{"zzqq": SENTINEL})
    second = probe(fn, *lead, **{"wwvv": SENTINEL})
    if first is None or second is None:
        # A keyword nothing declares was taken anyway, which only **kwargs
        # does. str.format is the one with no signature to say so.
        return names, "", True
    if any_kw:
        raise SystemExit(f"{what}: **kwargs but a keyword was refused")
    if first[1] == second[1]:
        return names, first[1], False
    # The message names the keyword; both halves have to agree on the rest.
    a, b = first[1], second[1]
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    j = 0
    while j < len(a) - i and j < len(b) - i and a[len(a) - 1 - j] == b[len(b) - 1 - j]:
        j += 1
    if a[i : len(a) - j] != "zzqq" or b[i : len(b) - j] != "wwvv":
        raise SystemExit(f"{what}: cannot read a keyword out of {a!r} and {b!r}")
    return names, a[:i] + "%s" + a[len(a) - j :], False


def describe(tname: str, mname: str) -> dict:
    raw = inspect.getattr_static(TYPES[tname], mname)
    fn = getattr(TYPES[tname], mname)
    # dict.fromkeys and str.maketrans are bound to the class, not to an
    # instance, so a template's `d.fromkeys(x)` passes no receiver at all.
    bound_to_class = isinstance(raw, (classmethod, staticmethod)) or (
        getattr(fn, "__self__", None) is TYPES[tname]
    )
    lead = () if bound_to_class else (RECEIVERS[tname],)
    what = f"{tname}.{mname}"

    MAX = 8
    msgs = {
        n: is_arity_error(probe(fn, *lead, *([SENTINEL] * n)), n)
        for n in range(MAX + 1)
    }
    accepted = [n for n in range(MAX + 1) if msgs[n] is None]
    if not accepted:
        raise SystemExit(f"{what}: no argument count was accepted")
    lo, hi = min(accepted), max(accepted)
    if accepted != list(range(lo, hi + 1)):
        raise SystemExit(f"{what}: accepted counts are not a range: {accepted}")
    unbounded = hi == MAX

    few = ""
    if lo > 0:
        if lo >= 2:
            few = substitute(msgs[lo - 2], msgs[lo - 1], lo - 2, lo - 1, what)
        else:
            few = one_count_template(msgs[0], 0, what)
        if few % (lo - 1) != msgs[lo - 1]:
            raise SystemExit(f"{what}: the too-few template does not reproduce itself")
    many = ""
    if not unbounded:
        many = substitute(msgs[hi + 1], msgs[hi + 2], hi + 1, hi + 2, what)

    kw_names, kw_message, any_kw = keyword_rule(fn, lead, what)
    return {
        "min": lo,
        "max": -1 if unbounded else hi,
        "few": few,
        "many": many,
        "kwNames": kw_names,
        "kwMessage": kw_message,
        "anyKw": any_kw,
        "classBound": bound_to_class,
    }


def go_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gojja2_methods() -> dict[str, list[str]]:
    """The methods gojja2 implements, read out of its own tables."""
    txt = METHODS_GO.read_text(encoding="utf-8")
    bytes_txt = BYTES_GO.read_text(encoding="utf-8")

    def table(src: str, start: str, end: str) -> list[str]:
        i = src.index(start)
        j = src.index(end, i)
        return sorted(set(re.findall(r'^\t+"([a-z_0-9]+)":', src[i:j], re.M)))

    return {
        "str": table(txt, "\tstringMethods = map[string]", "\n\t}\n"),
        "list": table(txt, "var listMethods = map[string]", "\n}\n"),
        "dict": table(txt, "var dictMethods = map[string]", "\n}\n"),
        "tuple": table(txt, "var tupleMethods = map[string]", "\n}\n"),
        "bytes": table(bytes_txt, "\tm := map[string]fn{", "\n\treturn m\n}"),
    }


def main() -> int:
    rows = []
    n = 0
    for tname, names in gojja2_methods().items():
        for mname in names:
            if not hasattr(TYPES[tname], mname):
                print(f"skipped {tname}.{mname}: not a CPython method", file=sys.stderr)
                continue
            d = describe(tname, mname)
            kw = ", ".join(f'"{k}"' for k in d["kwNames"])
            rows.append(
                f'\t"{tname}.{mname}": {{minArgs: {d["min"]}, maxArgs: {d["max"]}, '
                f'fewMessage: {go_string(d["few"])}, '
                f'manyMessage: {go_string(d["many"])}, '
                f"kwNames: []string{{{kw}}}, "
                f'kwMessage: {go_string(d["kwMessage"])}, '
                f'anyKw: {str(d["anyKw"]).lower()}}},\n'
            )
            n += 1
    DST.write_text(
        HEADER.format(python=sys.version.split()[0], rows="".join(sorted(rows))),
        encoding="utf-8",
    )
    print(f"wrote {n} method signatures into {DST.relative_to(ROOT)}", file=sys.stderr)
    _ = jinja2.__version__  # the pinned environment is the one that was probed
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
