#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the character class jinja2's lexer matches a name out of.

jinja2 tokenizes a name with `jinja2._identifier.pattern`, which is
`[\\w<extra>]+`: Python's `\\w` at run time, plus 2,231 code points frozen into
that module when jinja2 was released. Then -- and this is the half that matters
-- it checks `value.isidentifier()` on what it matched and raises
"Invalid character in identifier" if that fails.

So the class is deliberately *wider* than an identifier, and the two phases give
three different answers a one-phase rule cannot:

  * `a\\u00b7` is accepted. MIDDLE DOT is one of the frozen extras and
    `"a\\u00b7".isidentifier()` is True, so jinja2 renders where a rule built
    from Unicode categories refuses.
  * `a\\u0898` is refused, at the character. That combining mark is neither `\\w`
    nor one of the extras -- it was assigned after the extras were frozen -- so
    the name ends before it and nothing matches it: "unexpected char". A rule
    that reads Mn as an identifier continuation *accepts* it, which is a template
    that works here and not there.
  * `a\\u00b2` is refused, at the *name*. SUPERSCRIPT TWO is `\\w`, so it is part
    of the match, and then isidentifier says no: "Invalid character in
    identifier" rather than "unexpected char".

The extras are frozen but `\\w` is not, so the class is asked of every
interpreter gojja2 reproduces: the pin's answer whole, and a delta for each
other version. The extras themselves came out identical on all four, which is
what "frozen" means -- but that is measured here rather than assumed.
"""

from __future__ import annotations

import subprocess
import sys

import pyversions

ROOT = pyversions.ROOT
DST = ROOT / "value" / "nameclass.go"
VERSIONS = pyversions.others()
DEFAULT = pyversions.default()

# Printed by the child interpreter: one line per code point in the class.
DUMPER = """
import sys
from jinja2._identifier import pattern as name_re
out = []
for cp in range(0x110000):
    if 0xD800 <= cp < 0xE000:
        continue
    m = name_re.match(chr(cp))
    if m is not None and m.end() == 1:
        out.append("%d\\n" % cp)
sys.stdout.write("".join(out))
"""


def dump(version: str) -> set[int]:
    """Ask one interpreter which code points its jinja2 name class holds."""
    proc = subprocess.run(
        ["uv", "run", "--python", version, "--with", "jinja2", "--no-project",
         "python", "-c", DUMPER],
        capture_output=True, text=True, check=True)
    out = {int(line) for line in proc.stdout.split()}
    if not out:
        raise SystemExit(f"no output from CPython {version}")
    sys.stderr.write(f"  CPython {version}: {len(out)} code points in the class\n")
    return out


def ranges(points: set[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in sorted(points):
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def range_table(name: str, points: set[int], doc: str) -> str:
    r16 = [r for r in ranges(points) if r[1] <= 0xFFFF]
    r32 = [r for r in ranges(points) if r[1] > 0xFFFF]
    lines = [doc, f"var {name} = &unicode.RangeTable{{"]
    if r16:
        lines.append("\tR16: []unicode.Range16{")
        lines += ["\t\t{0x%04x, 0x%04x, 1}," % r for r in r16]
        lines.append("\t},")
    if r32:
        lines.append("\tR32: []unicode.Range32{")
        lines += ["\t\t{0x%06x, 0x%06x, 1}," % r for r in r32]
        lines.append("\t},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    sys.stderr.write("asking each interpreter for jinja2's name class:\n")
    base = dump(DEFAULT)

    parts = ['''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_name_class.py. DO NOT EDIT.

package value

import "unicode"

// The character class jinja2's lexer matches a name out of, which is wider than
// an identifier on purpose: `jinja2._identifier.pattern` is `[\\w<extra>]+`, and
// the lexer then checks isidentifier() on what it matched. See
// tools/oracle/gen_name_class.py for the three answers that needs, and
// IsIdentifier for the second half.
//
// Regenerate with `make name-class`.''']

    parts.append(range_table(
        "nameClassDefault", base,
        "// nameClassDefault is the class for the pinned interpreter, whole: `\\w`\n"
        "// there plus jinja2's frozen extras. The extras are the same under every\n"
        f"// interpreter; `\\w` is not. {len(base)} code points."))

    rows = []
    for v in VERSIONS:
        suffix = v.replace(".", "")
        other = dump(v)
        delta = other ^ base
        parts.append(range_table(
            f"nameClassOther{suffix}", delta,
            f"// nameClassOther{suffix} is where CPython {v} and the pin disagree about\n"
            f"// the class, which is only ever `\\w` moving: a code point listed here\n"
            f"// answers the opposite of the pin's. {len(delta)} code points."))
        rows.append(f"\tPython{suffix}: nameClassOther{suffix},\n")

    parts.append(
        "// nameClassOther is every non-pinned interpreter's difference, by version.\n"
        "var nameClassOther = map[PythonVersion]*unicode.RangeTable{\n"
        + "".join(rows) + "}")

    DST.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    sys.stderr.write(f"wrote {DST.relative_to(ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
