#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the code points int() and float() read as decimal digits.

Python's int() and float() do not take ASCII digits. They run their argument
through _PyUnicode_TransformDecimalAndSpaceToASCII first, which replaces every
character carrying a *decimal* value with the ASCII digit of that value and
every whitespace character with a space. So int("٤٢") is 42, and so
is int("٤" + "2"): the scripts may even be mixed.

gojja2 read ASCII digits only, in both of the places it prepares numeric text,
so `{{ "٤٢"|int }}` answered the filter's default of 0 -- a wrong
number, silently, for any template handling localised digits.

*Decimal* is narrower than the other two numeric predicates, and the difference
is the point: SUPERSCRIPT TWO is isdigit, VULGAR FRACTION ONE HALF and ROMAN
NUMERAL FIVE are isnumeric, and int() refuses all three. Only Nd is taken, so
this is its own table rather than a reuse of strclass.go's.

Go's unicode.Nd is a superset -- 680 code points against CPython 3.11's 660,
because Go is on Unicode 15.0.0 and CPython 3.11 on 14.0.0. Using it directly
would accept twenty code points (Kawi and Nag Mundari digits) that the
specification rejects, so the table comes from the pinned CPython instead.

Every decimal code point falls in a run of ten consecutive ones valued 0 to 9,
so the table is just the sixty-six run starts and a value is r - start.
"""

from __future__ import annotations

import hashlib
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "value" / "decimaltable.go"
MAX = 0x110000


def decimal_values() -> dict[int, int]:
    out = {}
    for cp in range(MAX):
        try:
            out[cp] = unicodedata.decimal(chr(cp))
        except (ValueError, TypeError):
            pass
    return out


def runs(vals: dict[int, int]) -> list[int]:
    """The start of each run of ten consecutive digits valued 0 through 9."""
    starts: list[int] = []
    cps = sorted(vals)
    i = 0
    while i < len(cps):
        start = cps[i]
        if vals[start] != 0:
            raise SystemExit(f"U+{start:04X} has decimal value {vals[start]} "
                             "but starts a run; the table shape assumed here is wrong")
        for j in range(10):
            if i + j >= len(cps) or cps[i + j] != start + j or vals[cps[i + j]] != j:
                raise SystemExit(f"the run at U+{start:04X} is not ten consecutive "
                                 "digits; the table shape assumed here is wrong")
        starts.append(start)
        i += 10
    return starts


def main() -> int:
    vals = decimal_values()
    starts = runs(vals)

    # A digest over every code point, so a table that stops matching CPython
    # fails loudly rather than in one script nobody tests with.
    h = hashlib.sha256()
    for cp in range(MAX):
        h.update(f"{cp}\t{vals.get(cp, -1)}\n".encode())
    digest = h.hexdigest()

    rows = "\n".join(f"\t0x{s:04X}," for s in starts)
    DST.write_text(f'''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_decimal.py. DO NOT EDIT.

package value

// decimalRuns is the start of each run of ten consecutive code points that
// int() and float() read as the digits 0 through 9, in order. A code point's
// value is its distance from the start of the run holding it.
//
// This comes from the pinned CPython rather than from unicode.Nd, which is a
// superset: Go is on a later Unicode than CPython 3.11, and the extra code
// points would be accepted where the specification rejects them.
var decimalRuns = [...]rune{{
{rows}
}}

// decimalDigitCount is how many code points that is, for the test to check it
// walked the whole table.
const decimalDigitCount = {len(vals)}

// decimalDigitDigest is a sha256 over every code point in Unicode and the
// decimal value CPython gives it, or -1 where it gives none. decimal_test.go
// recomputes it from the table above, so a run that moves, gains a member or
// loses one fails the build.
//
// Regenerate with `make decimal` and read the diff: it is telling you either
// that Unicode moved or that the pinned CPython did.
const decimalDigitDigest = "{digest}"
''', encoding="utf-8")
    print(f"wrote {len(starts)} runs covering {len(vals)} decimal code points "
          f"into {DST.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
