#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the character references html.unescape resolves.

`|striptags` ends in markupsafe's unescape, which is Python's html.unescape,
which resolves every HTML 5 named reference -- 2231 of them, including the
uppercase spellings and the ones valid without a trailing semicolon -- plus
numeric references, with the standard's rules for the invalid ones.

A hand-written list of the eight entities somebody thought of gets eight of
them right and leaves `&AMP;` and `&copy;` sitting in the output. This is not a
list to curate, so it is taken from the same CPython this project grades
against.
"""

from __future__ import annotations

import html
import html.entities
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "entities.go"

HEADER = """// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_entities.py from CPython {version}. DO NOT EDIT.
//
// The character references Python's html.unescape resolves, which is where
// |striptags ends up: the HTML 5 named references, the code points the
// standard replaces rather than accepts, and the ones it drops entirely.

package gojja2

// htmlEntities maps a named reference -- without the leading "&", and with the
// trailing ";" where the standard requires one -- to the text it stands for.
var htmlEntities = map[string]string{{
{named}}}

// invalidCharrefs are the numeric references the standard resolves to a
// different character than the code point they name.
var invalidCharrefs = map[int]string{{
{charrefs}}}

// invalidCodepoints are the numeric references the standard drops.
var invalidCodepoints = map[int]bool{{
{codepoints}}}
"""


def go_string(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            cp = ord(ch)
            out.append("\\u%04x" % cp if cp <= 0xFFFF else "\\U%08x" % cp)
    out.append('"')
    return "".join(out)


def main() -> int:
    named = "".join(
        "\t%s: %s,\n" % (go_string(name), go_string(text))
        for name, text in sorted(html.entities.html5.items())
    )
    charrefs = "".join(
        "\t%d: %s,\n" % (num, go_string(text))
        for num, text in sorted(html._invalid_charrefs.items())
    )
    codepoints = "".join("\t%d: true,\n" % num for num in sorted(html._invalid_codepoints))
    DST.write_text(
        HEADER.format(
            version=".".join(str(n) for n in sys.version_info[:3]),
            named=named,
            charrefs=charrefs,
            codepoints=codepoints,
        ),
        encoding="utf-8",
    )
    print(
        "wrote %d named references, %d replaced and %d dropped code points into %s"
        % (
            len(html.entities.html5),
            len(html._invalid_charrefs),
            len(html._invalid_codepoints),
            DST.relative_to(ROOT),
        ),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
