#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write a digest over what CPython's UTF-8 decoder does to bad bytes.

`bytes.decode()` is not only "is this valid UTF-8". For every sequence it
refuses, CPython decides three further things that a template can see:

    the reason      invalid start byte / invalid continuation byte /
                    unexpected end of data
    how far it runs 1, 2 or 3 bytes, or the whole truncated tail -- which is
                    what makes the message say "byte 0xNN in position 3"
                    rather than "bytes in position 3-5"
    how it resumes  the error handler is called once per error, not once per
                    byte, so errors="replace" writes one U+FFFD for the whole
                    run and the walk continues past it

gojja2 decoded with utf8.DecodeRune and reported one bad byte at a time, which
got all three wrong for a truncated sequence -- `b"\\xf0\\x9f"` was two errors,
both "invalid continuation byte", and two replacement characters, where CPython
has one error, "unexpected end of data", over "position 0-1", and one U+FFFD.
It also called \\xc0 and \\xc1 continuation problems, where CPython rejects them
as start bytes before looking at what follows.

The rules are a state machine with sixteen ways out and no natural corpus, so
this walks it exhaustively instead: every one- and two-byte sequence, and every
three- and four-byte sequence over the bytes that sit on a boundary. Each one
is decoded three ways and the transcript is hashed. The digest is one constant,
and `codecs_utf8_test.go` recomputes it from gojja2's decoder.

A failure means a sequence moved. Regenerate with `make utf8` and, to see
which, run this with --dump and diff it against the Go side's own --dump.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "utf8digest.go"

# The bytes a decision turns on: the ends of every continuation and lead range,
# the two overlong leads, the surrogate and out-of-range leads, and one
# ordinary ASCII byte to stand for the rest.
ALPHABET = [
    0x00, 0x41, 0x7F,
    0x80, 0x81, 0x8F, 0x90, 0x91, 0x9F, 0xA0, 0xA1, 0xBF,
    0xC0, 0xC1, 0xC2, 0xC3, 0xDF,
    0xE0, 0xE1, 0xEC, 0xED, 0xEE, 0xEF,
    0xF0, 0xF1, 0xF3, 0xF4, 0xF5, 0xFE, 0xFF,
]


def sequences():
    """Every case, in the order the digest hashes them."""
    for n in (1, 2):
        yield from itertools.product(range(256), repeat=n)
    for n in (3, 4):
        yield from itertools.product(ALPHABET, repeat=n)


def transcript(seq: tuple[int, ...]) -> str:
    """One line: the sequence and what the three handlers make of it."""
    b = bytes(seq)
    try:
        strict = "ok\t" + b.decode()
    except UnicodeDecodeError as e:
        strict = "err\t" + str(e)
    return "%s\t%s\treplace\t%s\tignore\t%s" % (
        b.hex(), strict, b.decode(errors="replace"), b.decode(errors="ignore"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", action="store_true",
                    help="print the transcript instead of writing the digest")
    args = ap.parse_args()

    h = hashlib.sha256()
    count = 0
    for seq in sequences():
        line = transcript(seq) + "\n"
        if args.dump:
            sys.stdout.write(line)
        h.update(line.encode("utf-8", "surrogatepass"))
        count += 1
    if args.dump:
        return 0

    digest = h.hexdigest()
    DST.write_text(f'''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_utf8.py. DO NOT EDIT.

package gojja2

// utf8DecodeCases is how many byte sequences the digest covers: every one- and
// two-byte sequence, and every three- and four-byte sequence over the {len(ALPHABET)}
// bytes a decision turns on.
const utf8DecodeCases = {count}

// utf8DecodeDigest is a sha256 over what CPython's UTF-8 decoder makes of each
// of those: the strict outcome -- the decoded text, or the exception's own
// message, reason and position range included -- and then what errors="replace"
// and errors="ignore" leave behind.
//
// The last two are not redundant. They are what pins the *size* of an error:
// the handler runs once per error rather than once per byte, so a decoder that
// splits one truncated sequence into two errors writes two replacement
// characters where CPython writes one, and no strict message would say so.
//
// Regenerate with `make utf8`. See the generator for how to find what moved.
const utf8DecodeDigest = "{digest}"
''', encoding="utf-8")
    print(f"wrote a digest over {count} byte sequences into "
          f"{DST.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
