#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Write the method-arity entries an older interpreter words differently.

method_arity.go is CPython's own wording for a call that does not fit a built-in
method's signature, probed out of the pinned interpreter. CPython rewords those
between releases -- 3.13 turned "count() takes at most 3 arguments (4 given)"
into "count expected at most 3 arguments, got 4", and "'zz' is an invalid keyword
argument for split()" into "split() got an unexpected keyword argument 'zz'".

No rule connects which methods moved to anything a generator could derive, so
this records the difference rather than deriving it: each version gets the
entries it words differently, and a method absent from a version's block answers
as the pin does.

Every interpreter is reached through `uv run --python`, so this needs no
virtualenvs of its own and cannot drift from the pin -- and it probes the pin
too, asserting the committed table is what the pinned interpreter actually says
before trusting it as the baseline.
"""

from __future__ import annotations

import re
import sys
import tempfile
from pathlib import Path

import pyversions

ROOT = pyversions.ROOT
DST = ROOT / "method_arity_other.go"
BASE = ROOT / "method_arity.go"
GEN = "tools/oracle/gen_methods.py"

# One row of the table. The value starts at the brace, so a gofmt-aligned file
# and a freshly generated one parse to the same thing.
ROW = re.compile(r'^\t"([\w.]+)":\s+(\{.*\}),$')

CONST = {v: f"value.Python{v.replace('.', '')}" for v in pyversions.ALL}

HEADER = '''// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_arity_matrix.py. DO NOT EDIT.

package gojja2

import "github.com/mgilbir/gojja2/value"

// methodArityOther is what a CPython other than the pinned one said about a
// call that does not fit a built-in method's signature.
//
// method_arity.go carries the pinned interpreter's wording in full; this
// carries only the entries another one words differently, because most of them
// are identical and a second full copy per version would be four tables to keep
// in step. A method absent here answers as the pin does.
//
// Regenerate with `make arity-matrix`.
var methodArityOther = map[value.PythonVersion]map[string]methodSignature{
'''


def rows(path: Path) -> dict[str, str]:
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW.match(line)
        if m:
            out[m.group(1)] = m.group(2)
    if not out:
        raise SystemExit(f"no table rows in {path}")
    return out


def probe(version: str, tmp: Path) -> dict[str, str]:
    """Ask one interpreter for the whole table."""
    out = tmp / f"method_arity-{version}.go"
    pyversions.run(version, [GEN, "--out", str(out)], capture_output=True)
    return rows(out)


def main() -> int:
    pin = pyversions.default()
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        probed = {v: probe(v, tmp) for v in pyversions.ALL}

    # The committed table is the baseline every block is a difference from, so
    # it has to be what the pin says. If it is not, the pin moved and
    # `make methodarity` was not rerun -- and every block below would then
    # record a difference from a table nothing produces.
    base = probed[pin]
    committed = rows(BASE)
    if committed != base:
        moved = sorted(set(committed) ^ set(base)) or sorted(
            k for k in base if committed.get(k) != base[k])
        raise SystemExit(
            f"method_arity.go is not what CPython {pin} says ({len(moved)} entries "
            f"differ, first: {moved[0]}). Run `make methodarity` first: this table "
            "records differences from the pinned interpreter's, so a stale "
            "baseline makes every one of them wrong.")

    parts = [HEADER]
    empty = []
    for v in pyversions.others():
        table = probed[v]
        diff = {k: val for k, val in table.items() if base.get(k) != val}
        missing = sorted(set(base) - set(table))
        if not diff:
            empty.append(v)
            continue
        body = "".join(f'\t\t"{k}": {diff[k]},\n' for k in sorted(diff))
        parts.append(f"\t// CPython {v}: {len(diff)} of the table's entries differ.\n")
        if missing:
            parts.append(f"\t// Absent there entirely: {', '.join(missing)}.\n")
        parts.append(f"\t{CONST[v]}: {{\n{body}\t}},\n")
        print(f"{v}: {len(diff)} overrides"
              + (f", {len(missing)} absent" if missing else ""), file=sys.stderr)
    parts.append("}\n")

    if empty:
        # Named rather than emitted as an empty block: a block recording no
        # difference is a line that can only rot.
        note = ("// " + ", ".join(empty) + (" is" if len(empty) == 1 else " are")
                + " absent because " + ("it words" if len(empty) == 1 else "they word")
                + " every entry exactly as the pin does.\n")
        parts[0] = parts[0].replace(
            "var methodArityOther", note + "var methodArityOther")
        print(f"no overrides needed for {', '.join(empty)}", file=sys.stderr)

    DST.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {DST.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
