#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Import cookiecutter project templates as conformance cases.

Cookiecutter templates are the one corpus in this project that arrives with a
context already attached: `cookiecutter.json` *is* the context, in JSON, chosen
by the template's author rather than synthesised. That makes them free breadth
-- no recorder, no proxies, no guessing.

What they add over the other corpora is the shape of a template that generates
a *file*: `{% raw %}` blocks wrapping another templating language, conditional
whole-file bodies, filters over a flat namespace, and Jinja in a path rather
than in a document. Several of them are Django templates being generated by
Jinja, which means a `{% raw %}` block containing `{% block %}` and `{{ var }}`
that must survive untouched -- a good test, and one nothing else here covers.

Context values are resolved the way cookiecutter resolves them, because they
refer to each other:

    "package_name": "{{ cookiecutter.project_name.replace(' ', '-') }}"

is rendered in order against the context built so far. That rendering happens
here, in Python, and only its result reaches the case, so it is not a
reimplementation gojja2 is ever graded against -- both sides are handed the
same finished strings.

Nothing is vendored. `make suites` clones each template at a pinned revision
into the gitignored third_party/, and the cases land in the gitignored
testdata/generated/.
"""

from __future__ import annotations

import collections
import json
import re
import shutil
import sys
from pathlib import Path

import jinja2

import provenance

ROOT = Path(__file__).resolve().parents[2]
DST = ROOT / "testdata" / "generated" / "cookiecutter"

SEPARATOR = "\n---\n"

# The clones, the license each carries, and the file its context lives in.
#
# That last field is not always cookiecutter.json. data-science moved to its
# own `ccds` command and left a deprecation notice behind, so reading the
# conventional name there yields a context of one string and every template
# renders undefineds.
SOURCES = [
    ("django", "cookiecutter_django", "cookiecutter/cookiecutter-django",
     "BSD-3-Clause", "cookiecutter.json"),
    ("pypackage", "cookiecutter_pypackage", "audreyfeldroy/cookiecutter-pypackage",
     "MIT", "cookiecutter.json"),
    ("datascience", "cookiecutter_datascience", "drivendata/cookiecutter-data-science",
     "MIT", "ccds.json"),
    ("hypermodern", "cookiecutter_hypermodern", "cjolowicz/cookiecutter-hypermodern-python",
     "MIT", "cookiecutter.json"),
]

# Machinery cookiecutter adds to the environment that is not jinja2's.
# `{% now %}` comes from jinja2_time and reads the clock, so no golden for it
# could stay correct; slugify, jsonify, random_ascii_string and uuid4 are
# cookiecutter extensions. A template using any of them is dropped rather than
# graded against an environment it was not written for.
COOKIECUTTER_ONLY = re.compile(
    r"\{%-?\s*now\b|\bslugify\b|\bjsonify\b|\brandom_ascii_string\b|\buuid4\b"
)

# A template with no delimiter is a plain file being copied, not a template.
HAS_JINJA = re.compile(r"\{\{|\{%|\{#")

# Generated projects carry lockfiles and vendored assets that are megabytes of
# no Jinja at all; the cap keeps one from becoming a case.
MAX_BYTES = 100_000


def load_context(repo: Path, config: str) -> dict:
    """Read the template's context file and resolve it as cookiecutter does."""
    raw = json.loads((repo / config).read_text(encoding="utf-8"))

    # A list value is a choice, and cookiecutter's default is the first entry.
    # A private key (leading underscore) is configuration rather than context,
    # but it stays readable from a template, so it is kept as it is.
    env = jinja2.Environment()
    resolved: dict = {}
    for key, value in raw.items():
        if isinstance(value, list):
            value = value[0] if value else ""
        if isinstance(value, str) and not key.startswith("_"):
            try:
                value = env.from_string(value).render(cookiecutter=dict(resolved))
            except jinja2.TemplateError:
                # A value that will not render stays literal. It is still a
                # string, so the case is still comparable; it just reads oddly.
                pass
        resolved[key] = value
    return resolved


def template_root(repo: Path) -> Path | None:
    """The `{{ cookiecutter.x }}` directory a template generates from."""
    for child in sorted(repo.iterdir()):
        if child.is_dir() and HAS_JINJA.search(child.name):
            return child
    return None


def readable(path: Path) -> str | None:
    """File contents, or None if it is binary or too large to be a case."""
    try:
        if path.stat().st_size > MAX_BYTES:
            return None
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def path_templates(root: Path) -> set[str]:
    """Jinja found in file and directory *names* rather than in contents.

    Cookiecutter renders a path as a template too, so `{{ cookiecutter.x }}.md`
    is a real template -- a one-liner, but one that exercises the expression
    language somewhere nothing else in the corpus puts it.
    """
    found: set[str] = set()
    for path in root.rglob("*"):
        for part in path.relative_to(root.parent).parts:
            if HAS_JINJA.search(part):
                found.add(part)
    return found


def main() -> int:
    env = jinja2.Environment()
    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True)

    seen: set[str] = set()
    kept = 0
    dropped: list[tuple[str, str]] = []
    missing: list[str] = []

    for tier, directory, _repo, _license, config in SOURCES:
        repo = ROOT / "third_party" / directory
        if not (repo / config).is_file():
            missing.append(f"{directory} (no {config})")
            continue

        context = {"cookiecutter": load_context(repo, config)}
        root = template_root(repo)
        if root is None:
            missing.append(f"{directory} (no template directory)")
            continue

        sources: list[tuple[str, str]] = []
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            text = readable(path)
            if text is not None:
                sources.append((path.relative_to(root.parent).as_posix(), text))
        # A path is a template in its own right.
        sources += [(f"<path> {name}", name) for name in sorted(path_templates(root))]

        for name, text in sources:
            case, reason = convert(env, tier, name, text, context, seen)
            if case is None:
                dropped.append((f"{tier}/{name}", reason))
                continue
            (DST / case).write_text(
                json.dumps(context, ensure_ascii=False, indent=2) + SEPARATOR + text,
                encoding="utf-8",
            )
            kept += 1

    if missing and kept == 0:
        print("no cookiecutter templates found; run `make suites` first", file=sys.stderr)
        return 1

    (DST / "SOURCES.md").write_text(sources_md(kept, dropped, missing), encoding="utf-8")
    print(
        f"imported {kept} cookiecutter cases into {DST.relative_to(ROOT)} "
        f"({len(dropped)} dropped)",
        file=sys.stderr,
    )
    return 0


def convert(
    env: jinja2.Environment,
    tier: str,
    name: str,
    text: str,
    context: dict,
    seen: set[str],
) -> tuple[str | None, str]:
    """Decide whether one file becomes a case, and under what filename."""
    if not HAS_JINJA.search(text):
        return None, "no template syntax; cookiecutter copies it verbatim"
    if COOKIECUTTER_ONLY.search(text):
        return None, "uses cookiecutter's own filters or reads the clock"
    if text in seen:
        return None, "duplicate of another template"
    # Compiling is jinja2's judgement rather than a guess of ours: an unknown
    # filter or a syntax error is a TemplateAssertionError here, and a case
    # that cannot compile has nothing to teach about rendering.
    try:
        env.from_string(text)
    except jinja2.TemplateError as exc:
        return None, f"does not compile: {type(exc).__name__}: {exc}"

    seen.add(text)
    stem = re.sub(r"[^A-Za-z0-9]+", "_", f"{tier}_{name}").strip("_").lower()
    return f"{stem[:110]}.jj2", ""


def sources_md(kept: int, dropped: list[tuple[str, str]], missing: list[str]) -> str:
    tally = collections.Counter(reason for _, reason in dropped)
    lines = [
        "# cookiecutter corpus",
        "",
        "Generated by tools/oracle/import_cookiecutter.py. Not vendored, not",
        "committed: `make import` rebuilds it from the clones in third_party/.",
        "",
        "## Sources",
        "",
        "| tier | repo | license | context |",
        "| --- | --- | --- | --- |",
    ]
    lines += [
        f"| {tier} | github.com/{repo} | {lic} | `{config}` |"
        for tier, _, repo, lic, config in SOURCES
    ]
    lines += [
        "",
        "Inputs only, as everywhere else: every golden is recorded from the",
        "pinned CPython jinja2.",
        "",
    ]
    lines += provenance.block(
        [
            (repo, ROOT / "third_party" / directory, lic)
            for _tier, directory, repo, lic, _config in SOURCES
        ]
    )
    lines += [
        "## Contexts",
        "",
        "Unlike every other imported corpus, these arrive with a context: each",
        "template's own `cookiecutter.json`, chosen by its author. A list value",
        "is a choice, and cookiecutter's default is its first entry. Values",
        "refer to each other -- `\"package_name\": \"{{ cookiecutter.project_name",
        ".replace(' ', '-') }}\"` -- so they are rendered in order against the",
        "context built so far, in Python, before the case is written. Only the",
        "finished strings reach the case, so both implementations are handed",
        "the same thing.",
        "",
        "`_copy_without_render` is not honoured. Cookiecutter uses it to copy",
        "some files verbatim rather than render them; here every file that",
        "contains Jinja and compiles becomes a case, which asks more of the",
        "engine rather than less.",
        "",
        f"## Cases ({kept})",
        "",
        f"## Dropped ({len(dropped)})",
        "",
    ]
    lines += [f"- {n} x {reason}" for reason, n in tally.most_common()]
    if missing:
        lines += ["", "## Not cloned", ""]
        lines += [f"- `{name}`" for name in missing]
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
