#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Import llama.cpp's Jinja tests as conformance cases.

llama.cpp replaced minja with an engine of its own in January 2026, so
tests/test-jinja.cpp is a fifth independent reading of the language, written
recently and aimed squarely at what chat templates use: whitespace control,
loops, `namespace`, string and array methods, filters and tests.

Its expected outputs encode llama.cpp's semantics and are discarded. Only the
templates and contexts are taken; CPython jinja2 is asked what each produces.

The environment is not a bare one. test-jinja.cpp carries its own Python
reference script, which builds

    SandboxedEnvironment(trim_blocks=True, lstrip_blocks=True,
                         extensions=[jinja2_ext.loopcontrols])

and then installs the same tojson override, strftime_now and raise_exception
that transformers does. That is the `transformers` profile, so every case here
carries it -- rendering these templates under a default environment would
diverge on whitespace alone.

Nothing is vendored. `make suites` clones llama.cpp into the gitignored
third_party/, and the cases land in the gitignored testdata/generated/.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

import cpplit
import provenance

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "third_party" / "llamacpp" / "tests" / "test-jinja.cpp"
DST = ROOT / "testdata" / "generated" / "llamacpp"

SEPARATOR = "\n---\n"

# strftime_now is frozen by the profile, so it is allowed. A real clock or a
# random source is not.
NONDETERMINISTIC = re.compile(r"\bnow\(\)|\brandom\b|\blipsum\b|0x[0-9a-f]{6,}")


def extract(src: str) -> tuple[list[tuple[str, str, dict]], list[str]]:
    """Return (name, template, context) triples, and skipped reasons."""
    cases: list[tuple[str, str, dict]] = []
    skipped: list[str] = []

    for _, args in cpplit.find_calls(src, "test_template"):
        # test_template(t, name, tmpl, vars, expect)
        if len(args) != 5:
            skipped.append(f"test_template() with {len(args)} arguments")
            continue
        try:
            name, _ = cpplit.read_concatenated_string(args[1], 0)
            template, _ = cpplit.read_concatenated_string(args[2], 0)
        except (cpplit.ParseError, ValueError):
            skipped.append("name or template is not a literal")
            continue
        try:
            context = cpplit.json_from_cpp(args[3])
        except (cpplit.ParseError, ValueError):
            skipped.append(f"unreadable context {args[3][:60]!r}")
            continue
        if not isinstance(context, dict):
            skipped.append("context is not an object")
            continue
        if NONDETERMINISTIC.search(template):
            skipped.append("reads the clock, a random source or an address")
            continue
        cases.append((name, template, context))
    return cases, skipped


def safe_stem(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower() or "case"


def main() -> int:
    if not SRC.is_file():
        print(f"{SRC} not found; run `make suites` first", file=sys.stderr)
        return 1

    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True)

    cases, skipped = extract(SRC.read_text(encoding="utf-8"))
    seen: set[tuple[str, str]] = set()
    count = 0
    for name, template, context in cases:
        key = (template, json.dumps(context, sort_keys=True))
        if key in seen:
            continue
        seen.add(key)

        header = {"__profile__": "transformers"}
        header.update(context)
        # The name makes a case readable; the hash keeps it unique and stable
        # as the suite is reordered.
        digest = hashlib.sha256("\0".join(key).encode()).hexdigest()[:8]
        stem = f"{safe_stem(name)}_{digest}"
        body = json.dumps(header, ensure_ascii=False, indent=2) + SEPARATOR + template
        (DST / f"{stem}.jj2").write_text(body, encoding="utf-8")
        count += 1

    (DST / "SOURCES.md").write_text(sources_md(count, skipped), encoding="utf-8")
    print(
        f"imported {count} llama.cpp cases into {DST.relative_to(ROOT)} "
        f"({len(skipped)} call(s) skipped)",
        file=sys.stderr,
    )
    return 0


def sources_md(count: int, skipped: list[str]) -> str:
    tally: dict[str, int] = {}
    for reason in skipped:
        tally[reason] = tally.get(reason, 0) + 1
    lines = [
        "# llamacpp corpus",
        "",
        "Generated by tools/oracle/import_llamacpp.py. Not vendored, not",
        "committed: `make import` rebuilds it from the clone in third_party/.",
        "",
        "## Source",
        "",
        "github.com/ggml-org/llama.cpp, tests/test-jinja.cpp -- MIT.",
        "",
        "Inputs only. llama.cpp's expected outputs encode its own engine's",
        "semantics and are discarded; every golden here is from CPython jinja2.",
        "",
    ]
    lines += provenance.block([
        ("ggml-org/llama.cpp", ROOT / "third_party" / "llamacpp", "MIT"),
    ])
    lines += [
        "## Environment",
        "",
        'Every case renders under `"__profile__": "transformers"`, which is the',
        "environment test-jinja.cpp's own Python reference script builds:",
        "trim_blocks, lstrip_blocks, the loopcontrols extension, the tojson",
        "override and the strftime_now and raise_exception globals.",
        "",
        f"## Cases ({count})",
        "",
        f"## Skipped calls ({len(skipped)})",
        "",
    ]
    if tally:
        lines += [f"- {n} x {reason}" for reason, n in sorted(tally.items(), key=lambda kv: -kv[1])]
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
