#!/usr/bin/env python3
# Copyright 2026 The gojja2 Authors
# SPDX-License-Identifier: Apache-2.0
"""Import google/minja's syntax tests as conformance cases.

minja is a C++ Jinja subset written for LLM chat templates, and its test suite
is a fourth independent reading of the language. Its expected outputs encode
minja's semantics and are discarded; only the templates, contexts and
whitespace options are taken, and CPython jinja2 is asked what each should
produce.

minja's own harness can render through Python jinja2 (`USE_JINJA2=1`), so the
templates were written to agree with it -- which makes a disagreement here a
sharp signal rather than a known fork.

Nothing is vendored. `make suites` clones minja into the gitignored
third_party/, and the cases land in the gitignored testdata/generated/.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

import cpplit
import provenance

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "third_party" / "minja" / "tests"
DST = ROOT / "testdata" / "generated" / "minja"

SEPARATOR = "\n---\n"

# The named Options constants minja's tests use, defined at the top of
# test-syntax.cpp. `{}` is the default: every flag false.
OPTION_SETS = {
    "{}": {},
    "lstrip_blocks": {"lstrip_blocks": True},
    "trim_blocks": {"trim_blocks": True},
    "lstrip_trim_blocks": {"trim_blocks": True, "lstrip_blocks": True},
}

# Constructs with no stable answer, or none this project implements.
NONDETERMINISTIC = re.compile(r"\bnow\(\)|\brandom\b|\blipsum\b|0x[0-9a-f]{6,}")


def extract(path: Path) -> tuple[list[tuple[str, dict, dict]], list[str]]:
    """Return (template, context, settings) triples, and skipped reasons."""
    src = path.read_text(encoding="utf-8")
    cases: list[tuple[str, dict, dict]] = []
    skipped: list[str] = []

    for _, args in cpplit.find_calls(src, "render"):
        if len(args) != 3:
            skipped.append(f"render() with {len(args)} arguments")
            continue
        try:
            template, _ = cpplit.read_concatenated_string(args[0], 0)
        except (cpplit.ParseError, ValueError):
            skipped.append("template is not a literal")
            continue

        options = args[2].strip()
        if options not in OPTION_SETS:
            skipped.append(f"unknown options {options!r}")
            continue

        try:
            context = cpplit.json_from_cpp(args[1])
        except (cpplit.ParseError, ValueError):
            skipped.append(f"unreadable context {args[1][:60]!r}")
            continue
        if not isinstance(context, dict):
            skipped.append("context is not an object")
            continue

        if NONDETERMINISTIC.search(template):
            skipped.append("reads the clock, a random source or an address")
            continue

        cases.append((template, context, OPTION_SETS[options]))
    return cases, skipped


def main() -> int:
    if not SRC.is_dir():
        print(f"{SRC} not found; run `make suites` first", file=sys.stderr)
        return 1

    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True)

    seen: set[tuple] = set()
    all_skipped: list[str] = []
    count = 0
    for path in sorted(SRC.glob("test-*.cpp")):
        stem = path.stem.removeprefix("test-").replace("-", "_")
        cases, skipped = extract(path)
        all_skipped += skipped
        for template, context, settings in cases:
            key = (template, json.dumps(context, sort_keys=True), json.dumps(settings, sort_keys=True))
            if key in seen:
                continue
            seen.add(key)

            header = dict(context)
            if settings:
                header["__settings__"] = settings
            # The hash keeps a case's name stable as the suite is reordered,
            # so one that regresses keeps its identity across a re-import.
            digest = hashlib.sha256("\0".join(key).encode()).hexdigest()[:10]
            body = json.dumps(header, ensure_ascii=False, indent=2) + SEPARATOR + template
            (DST / f"{stem}_{digest}.jj2").write_text(body, encoding="utf-8")
            count += 1

    (DST / "SOURCES.md").write_text(sources_md(count, all_skipped), encoding="utf-8")
    print(
        f"imported {count} minja cases into {DST.relative_to(ROOT)} "
        f"({len(all_skipped)} call(s) skipped)",
        file=sys.stderr,
    )
    return 0


def sources_md(count: int, skipped: list[str]) -> str:
    tally: dict[str, int] = {}
    for reason in skipped:
        tally[reason] = tally.get(reason, 0) + 1
    lines = [
        "# minja corpus",
        "",
        "Generated by tools/oracle/import_minja.py. Not vendored, not committed:",
        "`make import` rebuilds it from the clone in third_party/.",
        "",
        "## Source",
        "",
        "github.com/google/minja, tests/test-*.cpp -- MIT.",
        "",
        "Inputs only. minja's expected outputs encode minja's own semantics and",
        "are discarded; every golden here is recorded from CPython jinja2.",
        "",
    ]
    lines += provenance.block([
        ("google/minja", ROOT / "third_party" / "minja", "MIT"),
    ])
    lines += [
        f"## Cases ({count})",
        "",
        f"## Skipped calls ({len(skipped)})",
        "",
    ]
    if tally:
        lines += [f"- {n} x {reason}" for reason, n in sorted(tally.items(), key=lambda kv: -kv[1])]
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
