// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_decimal.py. DO NOT EDIT.

package value

// decimalRuns is the start of each run of ten consecutive code points that
// int() and float() read as the digits 0 through 9, in order. A code point's
// value is its distance from the start of the run holding it.
//
// This comes from the pinned CPython rather than from unicode.Nd, because the
// two track different Unicode releases and whichever is ahead has digits the
// other does not. Reading Go's table directly would answer for Go's Unicode,
// not for the specification's.
var decimalRuns = [...]rune{
	0x0030,
	0x0660,
	0x06F0,
	0x07C0,
	0x0966,
	0x09E6,
	0x0A66,
	0x0AE6,
	0x0B66,
	0x0BE6,
	0x0C66,
	0x0CE6,
	0x0D66,
	0x0DE6,
	0x0E50,
	0x0ED0,
	0x0F20,
	0x1040,
	0x1090,
	0x17E0,
	0x1810,
	0x1946,
	0x19D0,
	0x1A80,
	0x1A90,
	0x1B50,
	0x1BB0,
	0x1C40,
	0x1C50,
	0xA620,
	0xA8D0,
	0xA900,
	0xA9D0,
	0xA9F0,
	0xAA50,
	0xABF0,
	0xFF10,
	0x104A0,
	0x10D30,
	0x11066,
	0x110F0,
	0x11136,
	0x111D0,
	0x112F0,
	0x11450,
	0x114D0,
	0x11650,
	0x116C0,
	0x11730,
	0x118E0,
	0x11950,
	0x11C50,
	0x11D50,
	0x11DA0,
	0x11F50,
	0x16A60,
	0x16AC0,
	0x16B50,
	0x1D7CE,
	0x1D7D8,
	0x1D7E2,
	0x1D7EC,
	0x1D7F6,
	0x1E140,
	0x1E2F0,
	0x1E4F0,
	0x1E950,
	0x1FBF0,
}

// decimalDigitCount is how many code points that is, for the test to check it
// walked the whole table.
const decimalDigitCount = 680

// decimalDigitDigest is a sha256 over every code point in Unicode and the
// decimal value CPython gives it, or -1 where it gives none. decimal_test.go
// recomputes it from the table above, so a run that moves, gains a member or
// loses one fails the build.
//
// Regenerate with `make decimal` and read the diff: it is telling you either
// that Unicode moved or that the pinned CPython did.
const decimalDigitDigest = "8d0a2eb0b6a96acc093eee4670545461b0f75f78eda5872bdebbc1373ebecbbd"
