// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_unicode_matrix.py. DO NOT EDIT.

package value

import "unicode"

// The Unicode answers an older CPython gives where they differ from the
// default's, which the committed tables are built for.
//
// CPython carries its own Unicode, so the interpreter decides case mappings,
// which characters are digits, and how repr escapes them. Almost all of the
// difference is isprintable, and almost all of that is simply which characters
// had been assigned yet -- so it arrives in blocks and stores as ranges.
//
// Regenerate with `make unicode-matrix`, which asks each interpreter directly.

// alphaFixDefault is where the pinned CPython and Go disagree about
// str.isalpha. gojja2 asks unicode.IsLetter, which is a different
// Unicode release. 622 code points.
var alphaFixDefault = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableFixDefault is where the pinned CPython and Go disagree about
// str.isprintable, which is what repr escapes by. Almost all of it is
// simply which characters exist yet. 627 code points.
var printableFixDefault = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x2ffc, 0x2fff, 1},
		{0x31ef, 0x31ef, 1},
	},
	R32: []unicode.Range32{
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableOther311 is where CPython 3.11 and the pin disagree about
// isprintable, which is what repr escapes by. 5109 code points.
var printableOther311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0cf3, 0x0cf3, 1},
		{0x0ece, 0x0ece, 1},
		{0x2ffc, 0x2fff, 1},
		{0x31ef, 0x31ef, 1},
	},
	R32: []unicode.Range32{
		{0x010efd, 0x010eff, 1},
		{0x01123f, 0x011241, 1},
		{0x011b00, 0x011b09, 1},
		{0x011f00, 0x011f10, 1},
		{0x011f12, 0x011f3a, 1},
		{0x011f3e, 0x011f59, 1},
		{0x01342f, 0x01342f, 1},
		{0x013440, 0x013455, 1},
		{0x01b132, 0x01b132, 1},
		{0x01b155, 0x01b155, 1},
		{0x01d2c0, 0x01d2d3, 1},
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
		{0x01e08f, 0x01e08f, 1},
		{0x01e4d0, 0x01e4f9, 1},
		{0x01f6dc, 0x01f6dc, 1},
		{0x01f774, 0x01f776, 1},
		{0x01f77b, 0x01f77f, 1},
		{0x01f7d9, 0x01f7d9, 1},
		{0x01fa75, 0x01fa77, 1},
		{0x01fa87, 0x01fa88, 1},
		{0x01faad, 0x01faaf, 1},
		{0x01fabb, 0x01fabd, 1},
		{0x01fabf, 0x01fabf, 1},
		{0x01face, 0x01facf, 1},
		{0x01fada, 0x01fadb, 1},
		{0x01fae8, 0x01fae8, 1},
		{0x01faf7, 0x01faf8, 1},
		{0x02b739, 0x02b739, 1},
		{0x02ebf0, 0x02ee5d, 1},
		{0x031350, 0x0323af, 1},
	},
}

// upperOther311 is str.upper() where CPython 3.11 differs
// from the pin. 0 code points.
var upperOther311 = map[rune]string{}

// lowerOther311 is str.lower() where CPython 3.11 differs
// from the pin. 0 code points.
var lowerOther311 = map[rune]string{}

// titleOther311 is str.title() where CPython 3.11 differs
// from the pin. 0 code points.
var titleOther311 = map[rune]string{}

// foldOther311 is str.fold() where CPython 3.11 differs
// from the pin. 0 code points.
var foldOther311 = map[rune]string{}

// digitOther311 is where CPython 3.11 and the pin disagree
// about digit. 20 code points.
var digitOther311 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x011f50, 0x011f59, 1},
		{0x01e4f0, 0x01e4f9, 1},
	},
}

// numericOther311 is where CPython 3.11 and the pin disagree
// about numeric. 50 code points.
var numericOther311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x4e24, 0x4e24, 1},
		{0x4eac, 0x4eac, 1},
		{0x4fe9, 0x4fe9, 1},
		{0x5006, 0x5006, 1},
		{0x62d0, 0x62d0, 1},
		{0x6d1e, 0x6d1e, 1},
		{0x7695, 0x7695, 1},
		{0x79ed, 0x79ed, 1},
		{0x920e, 0x920e, 1},
		{0x94a9, 0x94a9, 1},
	},
	R32: []unicode.Range32{
		{0x011f50, 0x011f59, 1},
		{0x01d2c0, 0x01d2d3, 1},
		{0x01e4f0, 0x01e4f9, 1},
	},
}

// decimalOther311 is where CPython 3.11 and the pin disagree
// about decimal. 20 code points.
var decimalOther311 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x011f50, 0x011f59, 1},
		{0x01e4f0, 0x01e4f9, 1},
	},
}

// isLowerOther311 is where CPython 3.11 and the pin disagree
// about isLower. 73 code points.
var isLowerOther311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x10fc, 0x10fc, 1},
		{0xa7f2, 0xa7f4, 1},
		{0xab69, 0xab69, 1},
	},
	R32: []unicode.Range32{
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
	},
}

// isUpperOther311 is where CPython 3.11 and the pin disagree
// about isUpper. 0 code points.
var isUpperOther311 = &unicode.RangeTable{}

// isTitleOther311 is where CPython 3.11 and the pin disagree
// about isTitle. 0 code points.
var isTitleOther311 = &unicode.RangeTable{}

// isAlphaOther311 is where CPython 3.11 and the pin disagree
// about isAlpha. 4970 code points.
var isAlphaOther311 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x01123f, 0x011240, 1},
		{0x011f02, 0x011f02, 1},
		{0x011f04, 0x011f10, 1},
		{0x011f12, 0x011f33, 1},
		{0x01342f, 0x01342f, 1},
		{0x013441, 0x013446, 1},
		{0x01b132, 0x01b132, 1},
		{0x01b155, 0x01b155, 1},
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
		{0x01e4d0, 0x01e4eb, 1},
		{0x02b739, 0x02b739, 1},
		{0x02ebf0, 0x02ee5d, 1},
		{0x031350, 0x0323af, 1},
	},
}

// printableOther312 is where CPython 3.12 and the pin disagree about
// isprintable, which is what repr escapes by. 627 code points.
var printableOther312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x2ffc, 0x2fff, 1},
		{0x31ef, 0x31ef, 1},
	},
	R32: []unicode.Range32{
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// upperOther312 is str.upper() where CPython 3.12 differs
// from the pin. 0 code points.
var upperOther312 = map[rune]string{}

// lowerOther312 is str.lower() where CPython 3.12 differs
// from the pin. 0 code points.
var lowerOther312 = map[rune]string{}

// titleOther312 is str.title() where CPython 3.12 differs
// from the pin. 0 code points.
var titleOther312 = map[rune]string{}

// foldOther312 is str.fold() where CPython 3.12 differs
// from the pin. 0 code points.
var foldOther312 = map[rune]string{}

// digitOther312 is where CPython 3.12 and the pin disagree
// about digit. 0 code points.
var digitOther312 = &unicode.RangeTable{}

// numericOther312 is where CPython 3.12 and the pin disagree
// about numeric. 10 code points.
var numericOther312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x4e24, 0x4e24, 1},
		{0x4eac, 0x4eac, 1},
		{0x4fe9, 0x4fe9, 1},
		{0x5006, 0x5006, 1},
		{0x62d0, 0x62d0, 1},
		{0x6d1e, 0x6d1e, 1},
		{0x7695, 0x7695, 1},
		{0x79ed, 0x79ed, 1},
		{0x920e, 0x920e, 1},
		{0x94a9, 0x94a9, 1},
	},
}

// decimalOther312 is where CPython 3.12 and the pin disagree
// about decimal. 0 code points.
var decimalOther312 = &unicode.RangeTable{}

// isLowerOther312 is where CPython 3.12 and the pin disagree
// about isLower. 0 code points.
var isLowerOther312 = &unicode.RangeTable{}

// isUpperOther312 is where CPython 3.12 and the pin disagree
// about isUpper. 0 code points.
var isUpperOther312 = &unicode.RangeTable{}

// isTitleOther312 is where CPython 3.12 and the pin disagree
// about isTitle. 0 code points.
var isTitleOther312 = &unicode.RangeTable{}

// isAlphaOther312 is where CPython 3.12 and the pin disagree
// about isAlpha. 622 code points.
var isAlphaOther312 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableOther314 is where CPython 3.14 and the pin disagree about
// isprintable, which is what repr escapes by. 5185 code points.
var printableOther314 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0897, 0x0897, 1},
		{0x1b4e, 0x1b4f, 1},
		{0x1b7f, 0x1b7f, 1},
		{0x1c89, 0x1c8a, 1},
		{0x2427, 0x2429, 1},
		{0x31e4, 0x31e5, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d40, 0x010d65, 1},
		{0x010d69, 0x010d85, 1},
		{0x010d8e, 0x010d8f, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x010efc, 0x010efc, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113c0, 1},
		{0x0113c2, 0x0113c2, 1},
		{0x0113c5, 0x0113c5, 1},
		{0x0113c7, 0x0113ca, 1},
		{0x0113cc, 0x0113d5, 1},
		{0x0113d7, 0x0113d8, 1},
		{0x0113e1, 0x0113e2, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bc0, 0x011be1, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f5a, 0x011f5a, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x016139, 1},
		{0x016d40, 0x016d79, 1},
		{0x018cff, 0x018cff, 1},
		{0x01cc00, 0x01ccf9, 1},
		{0x01cd00, 0x01ceb3, 1},
		{0x01e5d0, 0x01e5fa, 1},
		{0x01e5ff, 0x01e5ff, 1},
		{0x01f8b2, 0x01f8bb, 1},
		{0x01f8c0, 0x01f8c1, 1},
		{0x01fa89, 0x01fa89, 1},
		{0x01fa8f, 0x01fa8f, 1},
		{0x01fabe, 0x01fabe, 1},
		{0x01fac6, 0x01fac6, 1},
		{0x01fadc, 0x01fadc, 1},
		{0x01fadf, 0x01fadf, 1},
		{0x01fae9, 0x01fae9, 1},
		{0x01fbcb, 0x01fbef, 1},
	},
}

// upperOther314 is str.upper() where CPython 3.14 differs
// from the pin. 27 code points.
var upperOther314 = map[rune]string{
	0x019b:  "\ua7dc",
	0x0264:  "\ua7cb",
	0x1c8a:  "\u1c89",
	0xa7cd:  "\ua7cc",
	0xa7db:  "\ua7da",
	0x10d70: "\U00010d50",
	0x10d71: "\U00010d51",
	0x10d72: "\U00010d52",
	0x10d73: "\U00010d53",
	0x10d74: "\U00010d54",
	0x10d75: "\U00010d55",
	0x10d76: "\U00010d56",
	0x10d77: "\U00010d57",
	0x10d78: "\U00010d58",
	0x10d79: "\U00010d59",
	0x10d7a: "\U00010d5a",
	0x10d7b: "\U00010d5b",
	0x10d7c: "\U00010d5c",
	0x10d7d: "\U00010d5d",
	0x10d7e: "\U00010d5e",
	0x10d7f: "\U00010d5f",
	0x10d80: "\U00010d60",
	0x10d81: "\U00010d61",
	0x10d82: "\U00010d62",
	0x10d83: "\U00010d63",
	0x10d84: "\U00010d64",
	0x10d85: "\U00010d65",
}

// lowerOther314 is str.lower() where CPython 3.14 differs
// from the pin. 27 code points.
var lowerOther314 = map[rune]string{
	0x1c89:  "\u1c8a",
	0xa7cb:  "\u0264",
	0xa7cc:  "\ua7cd",
	0xa7da:  "\ua7db",
	0xa7dc:  "\u019b",
	0x10d50: "\U00010d70",
	0x10d51: "\U00010d71",
	0x10d52: "\U00010d72",
	0x10d53: "\U00010d73",
	0x10d54: "\U00010d74",
	0x10d55: "\U00010d75",
	0x10d56: "\U00010d76",
	0x10d57: "\U00010d77",
	0x10d58: "\U00010d78",
	0x10d59: "\U00010d79",
	0x10d5a: "\U00010d7a",
	0x10d5b: "\U00010d7b",
	0x10d5c: "\U00010d7c",
	0x10d5d: "\U00010d7d",
	0x10d5e: "\U00010d7e",
	0x10d5f: "\U00010d7f",
	0x10d60: "\U00010d80",
	0x10d61: "\U00010d81",
	0x10d62: "\U00010d82",
	0x10d63: "\U00010d83",
	0x10d64: "\U00010d84",
	0x10d65: "\U00010d85",
}

// titleOther314 is str.title() where CPython 3.14 differs
// from the pin. 27 code points.
var titleOther314 = map[rune]string{
	0x019b:  "\ua7dc",
	0x0264:  "\ua7cb",
	0x1c8a:  "\u1c89",
	0xa7cd:  "\ua7cc",
	0xa7db:  "\ua7da",
	0x10d70: "\U00010d50",
	0x10d71: "\U00010d51",
	0x10d72: "\U00010d52",
	0x10d73: "\U00010d53",
	0x10d74: "\U00010d54",
	0x10d75: "\U00010d55",
	0x10d76: "\U00010d56",
	0x10d77: "\U00010d57",
	0x10d78: "\U00010d58",
	0x10d79: "\U00010d59",
	0x10d7a: "\U00010d5a",
	0x10d7b: "\U00010d5b",
	0x10d7c: "\U00010d5c",
	0x10d7d: "\U00010d5d",
	0x10d7e: "\U00010d5e",
	0x10d7f: "\U00010d5f",
	0x10d80: "\U00010d60",
	0x10d81: "\U00010d61",
	0x10d82: "\U00010d62",
	0x10d83: "\U00010d63",
	0x10d84: "\U00010d64",
	0x10d85: "\U00010d65",
}

// foldOther314 is str.fold() where CPython 3.14 differs
// from the pin. 27 code points.
var foldOther314 = map[rune]string{
	0x1c89:  "\u1c8a",
	0xa7cb:  "\u0264",
	0xa7cc:  "\ua7cd",
	0xa7da:  "\ua7db",
	0xa7dc:  "\u019b",
	0x10d50: "\U00010d70",
	0x10d51: "\U00010d71",
	0x10d52: "\U00010d72",
	0x10d53: "\U00010d73",
	0x10d54: "\U00010d74",
	0x10d55: "\U00010d75",
	0x10d56: "\U00010d76",
	0x10d57: "\U00010d77",
	0x10d58: "\U00010d78",
	0x10d59: "\U00010d79",
	0x10d5a: "\U00010d7a",
	0x10d5b: "\U00010d7b",
	0x10d5c: "\U00010d7c",
	0x10d5d: "\U00010d7d",
	0x10d5e: "\U00010d7e",
	0x10d5f: "\U00010d7f",
	0x10d60: "\U00010d80",
	0x10d61: "\U00010d81",
	0x10d62: "\U00010d82",
	0x10d63: "\U00010d83",
	0x10d64: "\U00010d84",
	0x10d65: "\U00010d85",
}

// digitOther314 is where CPython 3.14 and the pin disagree
// about digit. 80 code points.
var digitOther314 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// numericOther314 is where CPython 3.14 and the pin disagree
// about numeric. 80 code points.
var numericOther314 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// decimalOther314 is where CPython 3.14 and the pin disagree
// about decimal. 80 code points.
var decimalOther314 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// isLowerOther314 is where CPython 3.14 and the pin disagree
// about isLower. 25 code points.
var isLowerOther314 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c8a, 0x1c8a, 1},
		{0xa7cd, 0xa7cd, 1},
		{0xa7db, 0xa7db, 1},
	},
	R32: []unicode.Range32{
		{0x010d70, 0x010d85, 1},
	},
}

// isUpperOther314 is where CPython 3.14 and the pin disagree
// about isUpper. 27 code points.
var isUpperOther314 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isTitleOther314 is where CPython 3.14 and the pin disagree
// about isTitle. 27 code points.
var isTitleOther314 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isAlphaOther314 is where CPython 3.14 and the pin disagree
// about isAlpha. 4302 code points.
var isAlphaOther314 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c8a, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d4a, 0x010d65, 1},
		{0x010d6f, 0x010d85, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113b7, 1},
		{0x0113d1, 0x0113d1, 1},
		{0x0113d3, 0x0113d3, 1},
		{0x011bc0, 0x011be0, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x01611d, 1},
		{0x016d40, 0x016d6c, 1},
		{0x018cff, 0x018cff, 1},
		{0x01e5d0, 0x01e5ed, 1},
		{0x01e5f0, 0x01e5f0, 1},
	},
}

// unicodeOther is every non-pinned interpreter's overrides, by version.
// A version absent here answers exactly as the pinned one does.
var unicodeOther = map[PythonVersion]*UnicodeOverrides{
	Python311: {
		printable: printableOther311,
		upper:     upperOther311, lower: lowerOther311,
		title: titleOther311, fold: foldOther311,
		digit: digitOther311, numeric: numericOther311,
		decimal: decimalOther311,
		isLower: isLowerOther311, isUpper: isUpperOther311,
		isTitle: isTitleOther311, isAlpha: isAlphaOther311,
	},
	Python312: {
		printable: printableOther312,
		upper:     upperOther312, lower: lowerOther312,
		title: titleOther312, fold: foldOther312,
		digit: digitOther312, numeric: numericOther312,
		decimal: decimalOther312,
		isLower: isLowerOther312, isUpper: isUpperOther312,
		isTitle: isTitleOther312, isAlpha: isAlphaOther312,
	},
	Python314: {
		printable: printableOther314,
		upper:     upperOther314, lower: lowerOther314,
		title: titleOther314, fold: foldOther314,
		digit: digitOther314, numeric: numericOther314,
		decimal: decimalOther314,
		isLower: isLowerOther314, isUpper: isUpperOther314,
		isTitle: isTitleOther314, isAlpha: isAlphaOther314,
	},
}
