// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_unicode_older.py. DO NOT EDIT.

package value

import "unicode"

// The Unicode answers an older CPython gives where they differ from the
// default's, which the committed tables are built for.
//
// CPython carries its own Unicode, so the interpreter decides case mappings,
// which characters are digits, and how repr escapes them. Almost all of the
// difference is isprintable, and almost all of that is simply which characters
// had been assigned yet -- so it arrives in blocks and stores as ranges.
//
// Regenerate with `make unicode-matrix`, which asks each interpreter directly.

// alphaFixDefault is where the pinned CPython and Go disagree about
// str.isalpha. gojja2 asks unicode.IsLetter, which is a different
// Unicode release. 4924 code points.
var alphaFixDefault = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c8a, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d4a, 0x010d65, 1},
		{0x010d6f, 0x010d85, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113b7, 1},
		{0x0113d1, 0x0113d1, 1},
		{0x0113d3, 0x0113d3, 1},
		{0x011bc0, 0x011be0, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x01611d, 1},
		{0x016d40, 0x016d6c, 1},
		{0x018cff, 0x018cff, 1},
		{0x01e5d0, 0x01e5ed, 1},
		{0x01e5f0, 0x01e5f0, 1},
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableFixDefault is where the pinned CPython and Go disagree about
// str.isprintable, which is what repr escapes by. Almost all of it is
// simply which characters exist yet. 5812 code points.
var printableFixDefault = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0897, 0x0897, 1},
		{0x1b4e, 0x1b4f, 1},
		{0x1b7f, 0x1b7f, 1},
		{0x1c89, 0x1c8a, 1},
		{0x2427, 0x2429, 1},
		{0x2ffc, 0x2fff, 1},
		{0x31e4, 0x31e5, 1},
		{0x31ef, 0x31ef, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d40, 0x010d65, 1},
		{0x010d69, 0x010d85, 1},
		{0x010d8e, 0x010d8f, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x010efc, 0x010efc, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113c0, 1},
		{0x0113c2, 0x0113c2, 1},
		{0x0113c5, 0x0113c5, 1},
		{0x0113c7, 0x0113ca, 1},
		{0x0113cc, 0x0113d5, 1},
		{0x0113d7, 0x0113d8, 1},
		{0x0113e1, 0x0113e2, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bc0, 0x011be1, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f5a, 0x011f5a, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x016139, 1},
		{0x016d40, 0x016d79, 1},
		{0x018cff, 0x018cff, 1},
		{0x01cc00, 0x01ccf9, 1},
		{0x01cd00, 0x01ceb3, 1},
		{0x01e5d0, 0x01e5fa, 1},
		{0x01e5ff, 0x01e5ff, 1},
		{0x01f8b2, 0x01f8bb, 1},
		{0x01f8c0, 0x01f8c1, 1},
		{0x01fa89, 0x01fa89, 1},
		{0x01fa8f, 0x01fa8f, 1},
		{0x01fabe, 0x01fabe, 1},
		{0x01fac6, 0x01fac6, 1},
		{0x01fadc, 0x01fadc, 1},
		{0x01fadf, 0x01fadf, 1},
		{0x01fae9, 0x01fae9, 1},
		{0x01fbcb, 0x01fbef, 1},
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableOlder311 is where CPython 3.11 and the default disagree about
// isprintable, which is what repr escapes by. 10294 code points.
var printableOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0897, 0x0897, 1},
		{0x0cf3, 0x0cf3, 1},
		{0x0ece, 0x0ece, 1},
		{0x1b4e, 0x1b4f, 1},
		{0x1b7f, 0x1b7f, 1},
		{0x1c89, 0x1c8a, 1},
		{0x2427, 0x2429, 1},
		{0x2ffc, 0x2fff, 1},
		{0x31e4, 0x31e5, 1},
		{0x31ef, 0x31ef, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d40, 0x010d65, 1},
		{0x010d69, 0x010d85, 1},
		{0x010d8e, 0x010d8f, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x010efc, 0x010eff, 1},
		{0x01123f, 0x011241, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113c0, 1},
		{0x0113c2, 0x0113c2, 1},
		{0x0113c5, 0x0113c5, 1},
		{0x0113c7, 0x0113ca, 1},
		{0x0113cc, 0x0113d5, 1},
		{0x0113d7, 0x0113d8, 1},
		{0x0113e1, 0x0113e2, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011b00, 0x011b09, 1},
		{0x011bc0, 0x011be1, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f00, 0x011f10, 1},
		{0x011f12, 0x011f3a, 1},
		{0x011f3e, 0x011f5a, 1},
		{0x01342f, 0x01342f, 1},
		{0x013440, 0x013455, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x016139, 1},
		{0x016d40, 0x016d79, 1},
		{0x018cff, 0x018cff, 1},
		{0x01b132, 0x01b132, 1},
		{0x01b155, 0x01b155, 1},
		{0x01cc00, 0x01ccf9, 1},
		{0x01cd00, 0x01ceb3, 1},
		{0x01d2c0, 0x01d2d3, 1},
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
		{0x01e08f, 0x01e08f, 1},
		{0x01e4d0, 0x01e4f9, 1},
		{0x01e5d0, 0x01e5fa, 1},
		{0x01e5ff, 0x01e5ff, 1},
		{0x01f6dc, 0x01f6dc, 1},
		{0x01f774, 0x01f776, 1},
		{0x01f77b, 0x01f77f, 1},
		{0x01f7d9, 0x01f7d9, 1},
		{0x01f8b2, 0x01f8bb, 1},
		{0x01f8c0, 0x01f8c1, 1},
		{0x01fa75, 0x01fa77, 1},
		{0x01fa87, 0x01fa89, 1},
		{0x01fa8f, 0x01fa8f, 1},
		{0x01faad, 0x01faaf, 1},
		{0x01fabb, 0x01fabf, 1},
		{0x01fac6, 0x01fac6, 1},
		{0x01face, 0x01facf, 1},
		{0x01fada, 0x01fadc, 1},
		{0x01fadf, 0x01fadf, 1},
		{0x01fae8, 0x01fae9, 1},
		{0x01faf7, 0x01faf8, 1},
		{0x01fbcb, 0x01fbef, 1},
		{0x02b739, 0x02b739, 1},
		{0x02ebf0, 0x02ee5d, 1},
		{0x031350, 0x0323af, 1},
	},
}

// upperOlder311 is str.upper() where CPython 3.11 differs
// from the default. 27 code points.
var upperOlder311 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// lowerOlder311 is str.lower() where CPython 3.11 differs
// from the default. 27 code points.
var lowerOlder311 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// titleOlder311 is str.title() where CPython 3.11 differs
// from the default. 27 code points.
var titleOlder311 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// foldOlder311 is str.fold() where CPython 3.11 differs
// from the default. 27 code points.
var foldOlder311 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// digitOlder311 is where CPython 3.11 and the default disagree
// about digit. 100 code points.
var digitOlder311 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f50, 0x011f59, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e4f0, 0x01e4f9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// numericOlder311 is where CPython 3.11 and the default disagree
// about numeric. 130 code points.
var numericOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x4e24, 0x4e24, 1},
		{0x4eac, 0x4eac, 1},
		{0x4fe9, 0x4fe9, 1},
		{0x5006, 0x5006, 1},
		{0x62d0, 0x62d0, 1},
		{0x6d1e, 0x6d1e, 1},
		{0x7695, 0x7695, 1},
		{0x79ed, 0x79ed, 1},
		{0x920e, 0x920e, 1},
		{0x94a9, 0x94a9, 1},
	},
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f50, 0x011f59, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01d2c0, 0x01d2d3, 1},
		{0x01e4f0, 0x01e4f9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// decimalOlder311 is where CPython 3.11 and the default disagree
// about decimal. 100 code points.
var decimalOlder311 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f50, 0x011f59, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e4f0, 0x01e4f9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// isLowerOlder311 is where CPython 3.11 and the default disagree
// about isLower. 98 code points.
var isLowerOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x10fc, 0x10fc, 1},
		{0x1c8a, 0x1c8a, 1},
		{0xa7cd, 0xa7cd, 1},
		{0xa7db, 0xa7db, 1},
		{0xa7f2, 0xa7f4, 1},
		{0xab69, 0xab69, 1},
	},
	R32: []unicode.Range32{
		{0x010d70, 0x010d85, 1},
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
	},
}

// isUpperOlder311 is where CPython 3.11 and the default disagree
// about isUpper. 27 code points.
var isUpperOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isTitleOlder311 is where CPython 3.11 and the default disagree
// about isTitle. 27 code points.
var isTitleOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isAlphaOlder311 is where CPython 3.11 and the default disagree
// about isAlpha. 9272 code points.
var isAlphaOlder311 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c8a, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d4a, 0x010d65, 1},
		{0x010d6f, 0x010d85, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x01123f, 0x011240, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113b7, 1},
		{0x0113d1, 0x0113d1, 1},
		{0x0113d3, 0x0113d3, 1},
		{0x011bc0, 0x011be0, 1},
		{0x011f02, 0x011f02, 1},
		{0x011f04, 0x011f10, 1},
		{0x011f12, 0x011f33, 1},
		{0x01342f, 0x01342f, 1},
		{0x013441, 0x013446, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x01611d, 1},
		{0x016d40, 0x016d6c, 1},
		{0x018cff, 0x018cff, 1},
		{0x01b132, 0x01b132, 1},
		{0x01b155, 0x01b155, 1},
		{0x01df25, 0x01df2a, 1},
		{0x01e030, 0x01e06d, 1},
		{0x01e4d0, 0x01e4eb, 1},
		{0x01e5d0, 0x01e5ed, 1},
		{0x01e5f0, 0x01e5f0, 1},
		{0x02b739, 0x02b739, 1},
		{0x02ebf0, 0x02ee5d, 1},
		{0x031350, 0x0323af, 1},
	},
}

// printableOlder312 is where CPython 3.12 and the default disagree about
// isprintable, which is what repr escapes by. 5812 code points.
var printableOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0897, 0x0897, 1},
		{0x1b4e, 0x1b4f, 1},
		{0x1b7f, 0x1b7f, 1},
		{0x1c89, 0x1c8a, 1},
		{0x2427, 0x2429, 1},
		{0x2ffc, 0x2fff, 1},
		{0x31e4, 0x31e5, 1},
		{0x31ef, 0x31ef, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d40, 0x010d65, 1},
		{0x010d69, 0x010d85, 1},
		{0x010d8e, 0x010d8f, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x010efc, 0x010efc, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113c0, 1},
		{0x0113c2, 0x0113c2, 1},
		{0x0113c5, 0x0113c5, 1},
		{0x0113c7, 0x0113ca, 1},
		{0x0113cc, 0x0113d5, 1},
		{0x0113d7, 0x0113d8, 1},
		{0x0113e1, 0x0113e2, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bc0, 0x011be1, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f5a, 0x011f5a, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x016139, 1},
		{0x016d40, 0x016d79, 1},
		{0x018cff, 0x018cff, 1},
		{0x01cc00, 0x01ccf9, 1},
		{0x01cd00, 0x01ceb3, 1},
		{0x01e5d0, 0x01e5fa, 1},
		{0x01e5ff, 0x01e5ff, 1},
		{0x01f8b2, 0x01f8bb, 1},
		{0x01f8c0, 0x01f8c1, 1},
		{0x01fa89, 0x01fa89, 1},
		{0x01fa8f, 0x01fa8f, 1},
		{0x01fabe, 0x01fabe, 1},
		{0x01fac6, 0x01fac6, 1},
		{0x01fadc, 0x01fadc, 1},
		{0x01fadf, 0x01fadf, 1},
		{0x01fae9, 0x01fae9, 1},
		{0x01fbcb, 0x01fbef, 1},
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// upperOlder312 is str.upper() where CPython 3.12 differs
// from the default. 27 code points.
var upperOlder312 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// lowerOlder312 is str.lower() where CPython 3.12 differs
// from the default. 27 code points.
var lowerOlder312 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// titleOlder312 is str.title() where CPython 3.12 differs
// from the default. 27 code points.
var titleOlder312 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// foldOlder312 is str.fold() where CPython 3.12 differs
// from the default. 27 code points.
var foldOlder312 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// digitOlder312 is where CPython 3.12 and the default disagree
// about digit. 80 code points.
var digitOlder312 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// numericOlder312 is where CPython 3.12 and the default disagree
// about numeric. 90 code points.
var numericOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x4e24, 0x4e24, 1},
		{0x4eac, 0x4eac, 1},
		{0x4fe9, 0x4fe9, 1},
		{0x5006, 0x5006, 1},
		{0x62d0, 0x62d0, 1},
		{0x6d1e, 0x6d1e, 1},
		{0x7695, 0x7695, 1},
		{0x79ed, 0x79ed, 1},
		{0x920e, 0x920e, 1},
		{0x94a9, 0x94a9, 1},
	},
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// decimalOlder312 is where CPython 3.12 and the default disagree
// about decimal. 80 code points.
var decimalOlder312 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// isLowerOlder312 is where CPython 3.12 and the default disagree
// about isLower. 25 code points.
var isLowerOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c8a, 0x1c8a, 1},
		{0xa7cd, 0xa7cd, 1},
		{0xa7db, 0xa7db, 1},
	},
	R32: []unicode.Range32{
		{0x010d70, 0x010d85, 1},
	},
}

// isUpperOlder312 is where CPython 3.12 and the default disagree
// about isUpper. 27 code points.
var isUpperOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isTitleOlder312 is where CPython 3.12 and the default disagree
// about isTitle. 27 code points.
var isTitleOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isAlphaOlder312 is where CPython 3.12 and the default disagree
// about isAlpha. 4924 code points.
var isAlphaOlder312 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c8a, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d4a, 0x010d65, 1},
		{0x010d6f, 0x010d85, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113b7, 1},
		{0x0113d1, 0x0113d1, 1},
		{0x0113d3, 0x0113d3, 1},
		{0x011bc0, 0x011be0, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x01611d, 1},
		{0x016d40, 0x016d6c, 1},
		{0x018cff, 0x018cff, 1},
		{0x01e5d0, 0x01e5ed, 1},
		{0x01e5f0, 0x01e5f0, 1},
		{0x02ebf0, 0x02ee5d, 1},
	},
}

// printableOlder313 is where CPython 3.13 and the default disagree about
// isprintable, which is what repr escapes by. 5185 code points.
var printableOlder313 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x0897, 0x0897, 1},
		{0x1b4e, 0x1b4f, 1},
		{0x1b7f, 0x1b7f, 1},
		{0x1c89, 0x1c8a, 1},
		{0x2427, 0x2429, 1},
		{0x31e4, 0x31e5, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d40, 0x010d65, 1},
		{0x010d69, 0x010d85, 1},
		{0x010d8e, 0x010d8f, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x010efc, 0x010efc, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113c0, 1},
		{0x0113c2, 0x0113c2, 1},
		{0x0113c5, 0x0113c5, 1},
		{0x0113c7, 0x0113ca, 1},
		{0x0113cc, 0x0113d5, 1},
		{0x0113d7, 0x0113d8, 1},
		{0x0113e1, 0x0113e2, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bc0, 0x011be1, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x011f5a, 0x011f5a, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x016139, 1},
		{0x016d40, 0x016d79, 1},
		{0x018cff, 0x018cff, 1},
		{0x01cc00, 0x01ccf9, 1},
		{0x01cd00, 0x01ceb3, 1},
		{0x01e5d0, 0x01e5fa, 1},
		{0x01e5ff, 0x01e5ff, 1},
		{0x01f8b2, 0x01f8bb, 1},
		{0x01f8c0, 0x01f8c1, 1},
		{0x01fa89, 0x01fa89, 1},
		{0x01fa8f, 0x01fa8f, 1},
		{0x01fabe, 0x01fabe, 1},
		{0x01fac6, 0x01fac6, 1},
		{0x01fadc, 0x01fadc, 1},
		{0x01fadf, 0x01fadf, 1},
		{0x01fae9, 0x01fae9, 1},
		{0x01fbcb, 0x01fbef, 1},
	},
}

// upperOlder313 is str.upper() where CPython 3.13 differs
// from the default. 27 code points.
var upperOlder313 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// lowerOlder313 is str.lower() where CPython 3.13 differs
// from the default. 27 code points.
var lowerOlder313 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// titleOlder313 is str.title() where CPython 3.13 differs
// from the default. 27 code points.
var titleOlder313 = map[rune]string{
	0x019b:  "\u019b",
	0x0264:  "\u0264",
	0x1c8a:  "\u1c8a",
	0xa7cd:  "\ua7cd",
	0xa7db:  "\ua7db",
	0x10d70: "\U00010d70",
	0x10d71: "\U00010d71",
	0x10d72: "\U00010d72",
	0x10d73: "\U00010d73",
	0x10d74: "\U00010d74",
	0x10d75: "\U00010d75",
	0x10d76: "\U00010d76",
	0x10d77: "\U00010d77",
	0x10d78: "\U00010d78",
	0x10d79: "\U00010d79",
	0x10d7a: "\U00010d7a",
	0x10d7b: "\U00010d7b",
	0x10d7c: "\U00010d7c",
	0x10d7d: "\U00010d7d",
	0x10d7e: "\U00010d7e",
	0x10d7f: "\U00010d7f",
	0x10d80: "\U00010d80",
	0x10d81: "\U00010d81",
	0x10d82: "\U00010d82",
	0x10d83: "\U00010d83",
	0x10d84: "\U00010d84",
	0x10d85: "\U00010d85",
}

// foldOlder313 is str.fold() where CPython 3.13 differs
// from the default. 27 code points.
var foldOlder313 = map[rune]string{
	0x1c89:  "\u1c89",
	0xa7cb:  "\ua7cb",
	0xa7cc:  "\ua7cc",
	0xa7da:  "\ua7da",
	0xa7dc:  "\ua7dc",
	0x10d50: "\U00010d50",
	0x10d51: "\U00010d51",
	0x10d52: "\U00010d52",
	0x10d53: "\U00010d53",
	0x10d54: "\U00010d54",
	0x10d55: "\U00010d55",
	0x10d56: "\U00010d56",
	0x10d57: "\U00010d57",
	0x10d58: "\U00010d58",
	0x10d59: "\U00010d59",
	0x10d5a: "\U00010d5a",
	0x10d5b: "\U00010d5b",
	0x10d5c: "\U00010d5c",
	0x10d5d: "\U00010d5d",
	0x10d5e: "\U00010d5e",
	0x10d5f: "\U00010d5f",
	0x10d60: "\U00010d60",
	0x10d61: "\U00010d61",
	0x10d62: "\U00010d62",
	0x10d63: "\U00010d63",
	0x10d64: "\U00010d64",
	0x10d65: "\U00010d65",
}

// digitOlder313 is where CPython 3.13 and the default disagree
// about digit. 80 code points.
var digitOlder313 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// numericOlder313 is where CPython 3.13 and the default disagree
// about numeric. 80 code points.
var numericOlder313 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// decimalOlder313 is where CPython 3.13 and the default disagree
// about decimal. 80 code points.
var decimalOlder313 = &unicode.RangeTable{
	R32: []unicode.Range32{
		{0x010d40, 0x010d49, 1},
		{0x0116d0, 0x0116e3, 1},
		{0x011bf0, 0x011bf9, 1},
		{0x016130, 0x016139, 1},
		{0x016d70, 0x016d79, 1},
		{0x01ccf0, 0x01ccf9, 1},
		{0x01e5f1, 0x01e5fa, 1},
	},
}

// isLowerOlder313 is where CPython 3.13 and the default disagree
// about isLower. 25 code points.
var isLowerOlder313 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c8a, 0x1c8a, 1},
		{0xa7cd, 0xa7cd, 1},
		{0xa7db, 0xa7db, 1},
	},
	R32: []unicode.Range32{
		{0x010d70, 0x010d85, 1},
	},
}

// isUpperOlder313 is where CPython 3.13 and the default disagree
// about isUpper. 27 code points.
var isUpperOlder313 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isTitleOlder313 is where CPython 3.13 and the default disagree
// about isTitle. 27 code points.
var isTitleOlder313 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c89, 1},
		{0xa7cb, 0xa7cc, 1},
		{0xa7da, 0xa7da, 1},
		{0xa7dc, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x010d50, 0x010d65, 1},
	},
}

// isAlphaOlder313 is where CPython 3.13 and the default disagree
// about isAlpha. 4302 code points.
var isAlphaOlder313 = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x1c89, 0x1c8a, 1},
		{0xa7cb, 0xa7cd, 1},
		{0xa7da, 0xa7dc, 1},
	},
	R32: []unicode.Range32{
		{0x0105c0, 0x0105f3, 1},
		{0x010d4a, 0x010d65, 1},
		{0x010d6f, 0x010d85, 1},
		{0x010ec2, 0x010ec4, 1},
		{0x011380, 0x011389, 1},
		{0x01138b, 0x01138b, 1},
		{0x01138e, 0x01138e, 1},
		{0x011390, 0x0113b5, 1},
		{0x0113b7, 0x0113b7, 1},
		{0x0113d1, 0x0113d1, 1},
		{0x0113d3, 0x0113d3, 1},
		{0x011bc0, 0x011be0, 1},
		{0x013460, 0x0143fa, 1},
		{0x016100, 0x01611d, 1},
		{0x016d40, 0x016d6c, 1},
		{0x018cff, 0x018cff, 1},
		{0x01e5d0, 0x01e5ed, 1},
		{0x01e5f0, 0x01e5f0, 1},
	},
}

// unicodeOlder is every older interpreter's overrides, by version. A
// version absent here answers exactly as the default does.
var unicodeOlder = map[PythonVersion]*UnicodeOverrides{
	Python311: {
		printable: printableOlder311,
		upper:     upperOlder311, lower: lowerOlder311,
		title: titleOlder311, fold: foldOlder311,
		digit: digitOlder311, numeric: numericOlder311,
		decimal: decimalOlder311,
		isLower: isLowerOlder311, isUpper: isUpperOlder311,
		isTitle: isTitleOlder311, isAlpha: isAlphaOlder311,
	},
	Python312: {
		printable: printableOlder312,
		upper:     upperOlder312, lower: lowerOlder312,
		title: titleOlder312, fold: foldOlder312,
		digit: digitOlder312, numeric: numericOlder312,
		decimal: decimalOlder312,
		isLower: isLowerOlder312, isUpper: isUpperOlder312,
		isTitle: isTitleOlder312, isAlpha: isAlphaOlder312,
	},
	Python313: {
		printable: printableOlder313,
		upper:     upperOlder313, lower: lowerOlder313,
		title: titleOlder313, fold: foldOlder313,
		digit: digitOlder313, numeric: numericOlder313,
		decimal: decimalOlder313,
		isLower: isLowerOlder313, isUpper: isUpperOlder313,
		isTitle: isTitleOlder313, isAlpha: isAlphaOlder313,
	},
}
