// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_arity.py from jinja2 3.1.6. DO NOT EDIT.
//
// One entry per filter and test, carrying the signature CPython binds a call
// against. The counts are Python's, including the environment or context
// jinja2 injects as the first parameter, so that an arity error can report the
// numbers a template author would see on the other implementation.

package gojja2

// signature is a jinja2 filter or test as Python sees it.
type signature struct {
	// pyName is the function CPython names in the error.
	pyName string
	// params are the parameters a template can reach, the filtered value
	// or tested value first. A keyword may name any of them -- including
	// the first, which is how `x|upper(s=1)` becomes "multiple values".
	params []string
	// injected counts the parameters jinja2 supplies itself: the
	// environment, the context, or the eval context.
	injected int
	// required is how many parameters have no default, injected included.
	required int
	// total is the parameter count, injected included; -1 for *args.
	total int
	// varKw accepts any keyword, which is what **kwargs means.
	varKw bool
	// builtin marks one of Python's own functions, which jinja2 registers
	// directly -- abs, len, callable. A C function words its arity error
	// differently from a Python one, and a template author sees the
	// difference.
	builtin bool
}

// filterSignatures and testSignatures are keyed by the name a template uses.
// They are separate maps because four names -- float, lower, string and upper
// -- are both a filter and a test, with different signatures.
var filterSignatures = map[string]signature{
	"abs":            {pyName: "abs", params: []string{"x"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true},
	"attr":           {pyName: "do_attr", params: []string{"obj", "name"}, injected: 1, required: 3, total: 3, varKw: false, builtin: false},
	"batch":          {pyName: "do_batch", params: []string{"value", "linecount", "fill_with"}, injected: 0, required: 2, total: 3, varKw: false, builtin: false},
	"capitalize":     {pyName: "do_capitalize", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"center":         {pyName: "do_center", params: []string{"value", "width"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false},
	"count":          {pyName: "len", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true},
	"d":              {pyName: "do_default", params: []string{"value", "default_value", "boolean"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false},
	"default":        {pyName: "do_default", params: []string{"value", "default_value", "boolean"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false},
	"dictsort":       {pyName: "do_dictsort", params: []string{"value", "case_sensitive", "by", "reverse"}, injected: 0, required: 1, total: 4, varKw: false, builtin: false},
	"e":              {pyName: "escape", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"escape":         {pyName: "escape", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"filesizeformat": {pyName: "do_filesizeformat", params: []string{"value", "binary"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false},
	"first":          {pyName: "sync_do_first", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false},
	"float":          {pyName: "do_float", params: []string{"value", "default"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false},
	"forceescape":    {pyName: "do_forceescape", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"format":         {pyName: "do_format", params: []string{"value"}, injected: 0, required: 1, total: -1, varKw: true, builtin: false},
	"groupby":        {pyName: "sync_do_groupby", params: []string{"value", "attribute", "default", "case_sensitive"}, injected: 1, required: 3, total: 5, varKw: false, builtin: false},
	"indent":         {pyName: "do_indent", params: []string{"s", "width", "first", "blank"}, injected: 0, required: 1, total: 4, varKw: false, builtin: false},
	"int":            {pyName: "do_int", params: []string{"value", "default", "base"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false},
	"items":          {pyName: "do_items", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"join":           {pyName: "sync_do_join", params: []string{"value", "d", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false},
	"last":           {pyName: "do_last", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false},
	"length":         {pyName: "len", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true},
	"list":           {pyName: "sync_do_list", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"lower":          {pyName: "do_lower", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"map":            {pyName: "sync_do_map", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false},
	"max":            {pyName: "do_max", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false},
	"min":            {pyName: "do_min", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false},
	"pprint":         {pyName: "do_pprint", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"random":         {pyName: "do_random", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false},
	"reject":         {pyName: "sync_do_reject", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false},
	"rejectattr":     {pyName: "sync_do_rejectattr", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false},
	"replace":        {pyName: "do_replace", params: []string{"s", "old", "new", "count"}, injected: 1, required: 4, total: 5, varKw: false, builtin: false},
	"reverse":        {pyName: "do_reverse", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"round":          {pyName: "do_round", params: []string{"value", "precision", "method"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false},
	"safe":           {pyName: "do_mark_safe", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"select":         {pyName: "sync_do_select", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false},
	"selectattr":     {pyName: "sync_do_selectattr", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false},
	"slice":          {pyName: "sync_do_slice", params: []string{"value", "slices", "fill_with"}, injected: 0, required: 2, total: 3, varKw: false, builtin: false},
	"sort":           {pyName: "do_sort", params: []string{"value", "reverse", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 5, varKw: false, builtin: false},
	"string":         {pyName: "soft_str", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"striptags":      {pyName: "do_striptags", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"sum":            {pyName: "sync_do_sum", params: []string{"iterable", "attribute", "start"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false},
	"title":          {pyName: "do_title", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"tojson":         {pyName: "do_tojson", params: []string{"value", "indent"}, injected: 1, required: 2, total: 3, varKw: false, builtin: false},
	"trim":           {pyName: "do_trim", params: []string{"value", "chars"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false},
	"truncate":       {pyName: "do_truncate", params: []string{"s", "length", "killwords", "end", "leeway"}, injected: 1, required: 2, total: 6, varKw: false, builtin: false},
	"unique":         {pyName: "sync_do_unique", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false},
	"upper":          {pyName: "do_upper", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"urlencode":      {pyName: "do_urlencode", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"urlize":         {pyName: "do_urlize", params: []string{"value", "trim_url_limit", "nofollow", "target", "rel", "extra_schemes"}, injected: 1, required: 2, total: 7, varKw: false, builtin: false},
	"wordcount":      {pyName: "do_wordcount", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"wordwrap":       {pyName: "do_wordwrap", params: []string{"s", "width", "break_long_words", "wrapstring", "break_on_hyphens"}, injected: 1, required: 2, total: 6, varKw: false, builtin: false},
	"xmlattr":        {pyName: "do_xmlattr", params: []string{"d", "autospace"}, injected: 1, required: 2, total: 3, varKw: false, builtin: false},
}

var testSignatures = map[string]signature{
	"!=":          {pyName: "ne", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"<":           {pyName: "lt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"<=":          {pyName: "le", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"==":          {pyName: "eq", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	">":           {pyName: "gt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	">=":          {pyName: "ge", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"boolean":     {pyName: "test_boolean", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"callable":    {pyName: "callable", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true},
	"defined":     {pyName: "test_defined", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"divisibleby": {pyName: "test_divisibleby", params: []string{"value", "num"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false},
	"eq":          {pyName: "eq", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"equalto":     {pyName: "eq", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"escaped":     {pyName: "test_escaped", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"even":        {pyName: "test_even", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"false":       {pyName: "test_false", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"filter":      {pyName: "test_filter", params: []string{"value"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false},
	"float":       {pyName: "test_float", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"ge":          {pyName: "ge", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"greaterthan": {pyName: "gt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"gt":          {pyName: "gt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"in":          {pyName: "test_in", params: []string{"value", "seq"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false},
	"integer":     {pyName: "test_integer", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"iterable":    {pyName: "test_iterable", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"le":          {pyName: "le", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"lessthan":    {pyName: "lt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"lower":       {pyName: "test_lower", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"lt":          {pyName: "lt", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"mapping":     {pyName: "test_mapping", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"ne":          {pyName: "ne", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true},
	"none":        {pyName: "test_none", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"number":      {pyName: "test_number", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"odd":         {pyName: "test_odd", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"sameas":      {pyName: "test_sameas", params: []string{"value", "other"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false},
	"sequence":    {pyName: "test_sequence", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"string":      {pyName: "test_string", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"test":        {pyName: "test_test", params: []string{"value"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false},
	"true":        {pyName: "test_true", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"undefined":   {pyName: "test_undefined", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
	"upper":       {pyName: "test_upper", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false},
}
