// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_arity.py from jinja2 3.1.6. DO NOT EDIT.
//
// One entry per filter and test, carrying the signature CPython binds a call
// against. The counts are Python's, including the environment or context
// jinja2 injects as the first parameter, so that an arity error can report the
// numbers a template author would see on the other implementation.

package gojja2

// signature is a jinja2 filter or test as Python sees it.
type signature struct {
	// pyName is the function CPython names in the error.
	pyName string
	// pyCallName is what CPython prints for this function at a *call
	// site* rather than inside it -- module and qualified name, with
	// builtins left off -- which is the form an unpacking error uses.
	pyCallName string
	// params are the parameters a template can reach, the filtered value
	// or tested value first. A keyword may name any of them -- including
	// the first, which is how `x|upper(s=1)` becomes "multiple values".
	params []string
	// injected counts the parameters jinja2 supplies itself: the
	// environment, the context, or the eval context.
	injected int
	// required is how many parameters have no default, injected included.
	required int
	// total is the parameter count, injected included; -1 for *args.
	total int
	// varKw accepts any keyword, which is what **kwargs means.
	varKw bool
	// builtin marks one of Python's own functions, which jinja2 registers
	// directly -- abs, len, callable, and the operator.* comparisons. A C
	// function words its argument errors differently from a Python one,
	// and differently from each other, so the wordings are probed out of
	// CPython rather than derived from the signature.
	builtin bool
	// countMessage is what this C function says for any wrong number of
	// positional arguments, too few or too many alike, with the count
	// given. Empty for a Python function, which words it from the
	// signature instead.
	countMessage string
	// kwMessage is what it says when handed a keyword argument at all. It
	// names neither the keyword nor the count.
	kwMessage string
}

// filterSignatures and testSignatures are keyed by the name a template uses.
// They are separate maps because four names -- float, lower, string and upper
// -- are both a filter and a test, with different signatures.
var filterSignatures = map[string]signature{
	"abs":            {pyName: "abs", pyCallName: "abs()", params: []string{"x"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true, countMessage: "abs() takes exactly one argument (%d given)", kwMessage: "abs() takes no keyword arguments"},
	"attr":           {pyName: "do_attr", pyCallName: "jinja2.filters.do_attr()", params: []string{"obj", "name"}, injected: 1, required: 3, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"batch":          {pyName: "do_batch", pyCallName: "jinja2.filters.do_batch()", params: []string{"value", "linecount", "fill_with"}, injected: 0, required: 2, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"capitalize":     {pyName: "do_capitalize", pyCallName: "jinja2.filters.do_capitalize()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"center":         {pyName: "do_center", pyCallName: "jinja2.filters.do_center()", params: []string{"value", "width"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"count":          {pyName: "len", pyCallName: "len()", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true, countMessage: "len() takes exactly one argument (%d given)", kwMessage: "len() takes no keyword arguments"},
	"d":              {pyName: "do_default", pyCallName: "jinja2.filters.do_default()", params: []string{"value", "default_value", "boolean"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"default":        {pyName: "do_default", pyCallName: "jinja2.filters.do_default()", params: []string{"value", "default_value", "boolean"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"dictsort":       {pyName: "do_dictsort", pyCallName: "jinja2.filters.do_dictsort()", params: []string{"value", "case_sensitive", "by", "reverse"}, injected: 0, required: 1, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"e":              {pyName: "escape", pyCallName: "markupsafe.escape()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"escape":         {pyName: "escape", pyCallName: "markupsafe.escape()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"filesizeformat": {pyName: "do_filesizeformat", pyCallName: "jinja2.filters.do_filesizeformat()", params: []string{"value", "binary"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"first":          {pyName: "sync_do_first", pyCallName: "jinja2.filters.do_first()", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"float":          {pyName: "do_float", pyCallName: "jinja2.filters.do_float()", params: []string{"value", "default"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"forceescape":    {pyName: "do_forceescape", pyCallName: "jinja2.filters.do_forceescape()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"format":         {pyName: "do_format", pyCallName: "jinja2.filters.do_format()", params: []string{"value"}, injected: 0, required: 1, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"groupby":        {pyName: "sync_do_groupby", pyCallName: "jinja2.filters.do_groupby()", params: []string{"value", "attribute", "default", "case_sensitive"}, injected: 1, required: 3, total: 5, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"indent":         {pyName: "do_indent", pyCallName: "jinja2.filters.do_indent()", params: []string{"s", "width", "first", "blank"}, injected: 0, required: 1, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"int":            {pyName: "do_int", pyCallName: "jinja2.filters.do_int()", params: []string{"value", "default", "base"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"items":          {pyName: "do_items", pyCallName: "jinja2.filters.do_items()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"join":           {pyName: "sync_do_join", pyCallName: "jinja2.filters.do_join()", params: []string{"value", "d", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"last":           {pyName: "do_last", pyCallName: "jinja2.filters.do_last()", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"length":         {pyName: "len", pyCallName: "len()", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true, countMessage: "len() takes exactly one argument (%d given)", kwMessage: "len() takes no keyword arguments"},
	"list":           {pyName: "sync_do_list", pyCallName: "jinja2.filters.do_list()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"lower":          {pyName: "do_lower", pyCallName: "jinja2.filters.do_lower()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"map":            {pyName: "sync_do_map", pyCallName: "jinja2.filters.do_map()", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"max":            {pyName: "do_max", pyCallName: "jinja2.filters.do_max()", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"min":            {pyName: "do_min", pyCallName: "jinja2.filters.do_min()", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"pprint":         {pyName: "do_pprint", pyCallName: "jinja2.filters.do_pprint()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"random":         {pyName: "do_random", pyCallName: "jinja2.filters.do_random()", params: []string{"seq"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"reject":         {pyName: "sync_do_reject", pyCallName: "jinja2.filters.do_reject()", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"rejectattr":     {pyName: "sync_do_rejectattr", pyCallName: "jinja2.filters.do_rejectattr()", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"replace":        {pyName: "do_replace", pyCallName: "jinja2.filters.do_replace()", params: []string{"s", "old", "new", "count"}, injected: 1, required: 4, total: 5, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"reverse":        {pyName: "do_reverse", pyCallName: "jinja2.filters.do_reverse()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"round":          {pyName: "do_round", pyCallName: "jinja2.filters.do_round()", params: []string{"value", "precision", "method"}, injected: 0, required: 1, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"safe":           {pyName: "do_mark_safe", pyCallName: "jinja2.filters.do_mark_safe()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"select":         {pyName: "sync_do_select", pyCallName: "jinja2.filters.do_select()", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"selectattr":     {pyName: "sync_do_selectattr", pyCallName: "jinja2.filters.do_selectattr()", params: []string{"value"}, injected: 1, required: 2, total: -1, varKw: true, builtin: false, countMessage: "", kwMessage: ""},
	"slice":          {pyName: "sync_do_slice", pyCallName: "jinja2.filters.do_slice()", params: []string{"value", "slices", "fill_with"}, injected: 0, required: 2, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"sort":           {pyName: "do_sort", pyCallName: "jinja2.filters.do_sort()", params: []string{"value", "reverse", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 5, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"string":         {pyName: "soft_str", pyCallName: "markupsafe.soft_str()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"striptags":      {pyName: "do_striptags", pyCallName: "jinja2.filters.do_striptags()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"sum":            {pyName: "sync_do_sum", pyCallName: "jinja2.filters.do_sum()", params: []string{"iterable", "attribute", "start"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"title":          {pyName: "do_title", pyCallName: "jinja2.filters.do_title()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"tojson":         {pyName: "do_tojson", pyCallName: "jinja2.filters.do_tojson()", params: []string{"value", "indent"}, injected: 1, required: 2, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"trim":           {pyName: "do_trim", pyCallName: "jinja2.filters.do_trim()", params: []string{"value", "chars"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"truncate":       {pyName: "do_truncate", pyCallName: "jinja2.filters.do_truncate()", params: []string{"s", "length", "killwords", "end", "leeway"}, injected: 1, required: 2, total: 6, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"unique":         {pyName: "sync_do_unique", pyCallName: "jinja2.filters.do_unique()", params: []string{"value", "case_sensitive", "attribute"}, injected: 1, required: 2, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"upper":          {pyName: "do_upper", pyCallName: "jinja2.filters.do_upper()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"urlencode":      {pyName: "do_urlencode", pyCallName: "jinja2.filters.do_urlencode()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"urlize":         {pyName: "do_urlize", pyCallName: "jinja2.filters.do_urlize()", params: []string{"value", "trim_url_limit", "nofollow", "target", "rel", "extra_schemes"}, injected: 1, required: 2, total: 7, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"wordcount":      {pyName: "do_wordcount", pyCallName: "jinja2.filters.do_wordcount()", params: []string{"s"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"wordwrap":       {pyName: "do_wordwrap", pyCallName: "jinja2.filters.do_wordwrap()", params: []string{"s", "width", "break_long_words", "wrapstring", "break_on_hyphens"}, injected: 1, required: 2, total: 6, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"xmlattr":        {pyName: "do_xmlattr", pyCallName: "jinja2.filters.do_xmlattr()", params: []string{"d", "autospace"}, injected: 1, required: 2, total: 3, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
}

var testSignatures = map[string]signature{
	"!=":          {pyName: "ne", pyCallName: "_operator.ne()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "ne expected 2 arguments, got %d", kwMessage: "_operator.ne() takes no keyword arguments"},
	"<":           {pyName: "lt", pyCallName: "_operator.lt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "lt expected 2 arguments, got %d", kwMessage: "_operator.lt() takes no keyword arguments"},
	"<=":          {pyName: "le", pyCallName: "_operator.le()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "le expected 2 arguments, got %d", kwMessage: "_operator.le() takes no keyword arguments"},
	"==":          {pyName: "eq", pyCallName: "_operator.eq()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "eq expected 2 arguments, got %d", kwMessage: "_operator.eq() takes no keyword arguments"},
	">":           {pyName: "gt", pyCallName: "_operator.gt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "gt expected 2 arguments, got %d", kwMessage: "_operator.gt() takes no keyword arguments"},
	">=":          {pyName: "ge", pyCallName: "_operator.ge()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "ge expected 2 arguments, got %d", kwMessage: "_operator.ge() takes no keyword arguments"},
	"boolean":     {pyName: "test_boolean", pyCallName: "jinja2.tests.test_boolean()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"callable":    {pyName: "callable", pyCallName: "callable()", params: []string{"obj"}, injected: 0, required: 1, total: 1, varKw: false, builtin: true, countMessage: "callable() takes exactly one argument (%d given)", kwMessage: "callable() takes no keyword arguments"},
	"defined":     {pyName: "test_defined", pyCallName: "jinja2.tests.test_defined()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"divisibleby": {pyName: "test_divisibleby", pyCallName: "jinja2.tests.test_divisibleby()", params: []string{"value", "num"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"eq":          {pyName: "eq", pyCallName: "_operator.eq()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "eq expected 2 arguments, got %d", kwMessage: "_operator.eq() takes no keyword arguments"},
	"equalto":     {pyName: "eq", pyCallName: "_operator.eq()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "eq expected 2 arguments, got %d", kwMessage: "_operator.eq() takes no keyword arguments"},
	"escaped":     {pyName: "test_escaped", pyCallName: "jinja2.tests.test_escaped()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"even":        {pyName: "test_even", pyCallName: "jinja2.tests.test_even()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"false":       {pyName: "test_false", pyCallName: "jinja2.tests.test_false()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"filter":      {pyName: "test_filter", pyCallName: "jinja2.tests.test_filter()", params: []string{"value"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"float":       {pyName: "test_float", pyCallName: "jinja2.tests.test_float()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"ge":          {pyName: "ge", pyCallName: "_operator.ge()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "ge expected 2 arguments, got %d", kwMessage: "_operator.ge() takes no keyword arguments"},
	"greaterthan": {pyName: "gt", pyCallName: "_operator.gt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "gt expected 2 arguments, got %d", kwMessage: "_operator.gt() takes no keyword arguments"},
	"gt":          {pyName: "gt", pyCallName: "_operator.gt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "gt expected 2 arguments, got %d", kwMessage: "_operator.gt() takes no keyword arguments"},
	"in":          {pyName: "test_in", pyCallName: "jinja2.tests.test_in()", params: []string{"value", "seq"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"integer":     {pyName: "test_integer", pyCallName: "jinja2.tests.test_integer()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"iterable":    {pyName: "test_iterable", pyCallName: "jinja2.tests.test_iterable()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"le":          {pyName: "le", pyCallName: "_operator.le()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "le expected 2 arguments, got %d", kwMessage: "_operator.le() takes no keyword arguments"},
	"lessthan":    {pyName: "lt", pyCallName: "_operator.lt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "lt expected 2 arguments, got %d", kwMessage: "_operator.lt() takes no keyword arguments"},
	"lower":       {pyName: "test_lower", pyCallName: "jinja2.tests.test_lower()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"lt":          {pyName: "lt", pyCallName: "_operator.lt()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "lt expected 2 arguments, got %d", kwMessage: "_operator.lt() takes no keyword arguments"},
	"mapping":     {pyName: "test_mapping", pyCallName: "jinja2.tests.test_mapping()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"ne":          {pyName: "ne", pyCallName: "_operator.ne()", params: []string{"a", "b"}, injected: 0, required: 2, total: 2, varKw: false, builtin: true, countMessage: "ne expected 2 arguments, got %d", kwMessage: "_operator.ne() takes no keyword arguments"},
	"none":        {pyName: "test_none", pyCallName: "jinja2.tests.test_none()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"number":      {pyName: "test_number", pyCallName: "jinja2.tests.test_number()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"odd":         {pyName: "test_odd", pyCallName: "jinja2.tests.test_odd()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"sameas":      {pyName: "test_sameas", pyCallName: "jinja2.tests.test_sameas()", params: []string{"value", "other"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"sequence":    {pyName: "test_sequence", pyCallName: "jinja2.tests.test_sequence()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"string":      {pyName: "test_string", pyCallName: "jinja2.tests.test_string()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"test":        {pyName: "test_test", pyCallName: "jinja2.tests.test_test()", params: []string{"value"}, injected: 1, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"true":        {pyName: "test_true", pyCallName: "jinja2.tests.test_true()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"undefined":   {pyName: "test_undefined", pyCallName: "jinja2.tests.test_undefined()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"upper":       {pyName: "test_upper", pyCallName: "jinja2.tests.test_upper()", params: []string{"value"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
}

// runtimeSignatures covers the callables a template reaches that are neither
// filters nor tests: the globals, the methods on what they return, and the
// objects the renderer itself puts in scope -- loop and a block reference.
// They are keyed by the name CPython puts in the error rather than by the
// template's name, because several are classes whose methods each bind
// separately.
var runtimeSignatures = map[string]signature{
	"BlockReference.__call__": {pyName: "BlockReference.__call__", pyCallName: "jinja2.runtime.BlockReference.__call__()", params: []string{"self"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"Cycler.__init__":         {pyName: "Cycler.__init__", pyCallName: "jinja2.utils.Cycler.__init__()", params: []string{"self"}, injected: 0, required: 1, total: -1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"Cycler.next":             {pyName: "Cycler.next", pyCallName: "jinja2.utils.Cycler.next()", params: []string{"self"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"Cycler.reset":            {pyName: "Cycler.reset", pyCallName: "jinja2.utils.Cycler.reset()", params: []string{"self"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"Joiner.__call__":         {pyName: "Joiner.__call__", pyCallName: "jinja2.utils.Joiner.__call__()", params: []string{"self"}, injected: 0, required: 1, total: 1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"Joiner.__init__":         {pyName: "Joiner.__init__", pyCallName: "jinja2.utils.Joiner.__init__()", params: []string{"self", "sep"}, injected: 0, required: 1, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"LoopContext.__call__":    {pyName: "LoopContext.__call__", pyCallName: "jinja2.runtime.LoopContext.__call__()", params: []string{"self", "iterable"}, injected: 0, required: 2, total: 2, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"LoopContext.changed":     {pyName: "LoopContext.changed", pyCallName: "jinja2.runtime.LoopContext.changed()", params: []string{"self"}, injected: 0, required: 1, total: -1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"LoopContext.cycle":       {pyName: "LoopContext.cycle", pyCallName: "jinja2.runtime.LoopContext.cycle()", params: []string{"self"}, injected: 0, required: 1, total: -1, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
	"generate_lorem_ipsum":    {pyName: "generate_lorem_ipsum", pyCallName: "jinja2.utils.generate_lorem_ipsum()", params: []string{"n", "html", "min", "max"}, injected: 0, required: 0, total: 4, varKw: false, builtin: false, countMessage: "", kwMessage: ""},
}

// range is a C function with two wordings for a wrong count rather than one,
// so it does not fit the single countMessage a builtin signature carries.
const (
	rangeFewMessage  = "range expected at least 1 argument, got 0"
	rangeManyMessage = "range expected at most 3 arguments, got %d"
	rangeKwMessage   = "range() takes no keyword arguments"
)
