// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_methods.py from CPython 3.14.7. DO NOT EDIT.
//
// One entry per built-in method a template can call, carrying what CPython
// accepts and what it says when it does not. The wordings are probed rather
// than derived: a method that takes nothing, one that takes exactly one, and
// one with an optional second all word it differently, and no rule connects
// the wording to the signature.

package gojja2

// methodSignature is a built-in method as CPython binds a call to it.
type methodSignature struct {
	// minArgs and maxArgs bound the positional count, self excluded.
	// maxArgs is -1 when the method takes any number.
	minArgs, maxArgs int
	// fewMessage and manyMessage carry the offending count as %d. They are
	// the same string when CPython words both directions alike, and
	// fewMessage is empty when no call can be too short.
	fewMessage, manyMessage string
	// kwNames are the keyword arguments the method accepts, if any.
	kwNames []string
	// kwMessage is what it says when handed a keyword it does not take. It
	// carries the name as %s when CPython includes it, and nothing when it
	// does not.
	kwMessage string
	// anyKw marks a method that takes **kwargs, so no keyword is refused.
	anyKw bool
}

// methodSignatures is keyed by "<type>.<method>", the type being the receiver's
// Python name.
var methodSignatures = map[string]methodSignature{
	"bytes.capitalize":   {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.capitalize() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.capitalize() takes no keyword arguments", anyKw: false},
	"bytes.center":       {minArgs: 1, maxArgs: 2, fewMessage: "center expected at least 1 argument, got %d", manyMessage: "center expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.center() takes no keyword arguments", anyKw: false},
	"bytes.count":        {minArgs: 1, maxArgs: 3, fewMessage: "count expected at least 1 argument, got %d", manyMessage: "count expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.count() takes no keyword arguments", anyKw: false},
	"bytes.decode":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "decode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "decode() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.endswith":     {minArgs: 1, maxArgs: 3, fewMessage: "endswith expected at least 1 argument, got %d", manyMessage: "endswith expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.endswith() takes no keyword arguments", anyKw: false},
	"bytes.expandtabs":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "expandtabs() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.find":         {minArgs: 1, maxArgs: 3, fewMessage: "find expected at least 1 argument, got %d", manyMessage: "find expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.find() takes no keyword arguments", anyKw: false},
	"bytes.fromhex":      {minArgs: 1, maxArgs: 1, fewMessage: "bytes.fromhex() takes exactly one argument (%d given)", manyMessage: "bytes.fromhex() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.fromhex() takes no keyword arguments", anyKw: false},
	"bytes.hex":          {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "hex() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "bytes_per_sep"}, kwMessage: "hex() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.index":        {minArgs: 1, maxArgs: 3, fewMessage: "index expected at least 1 argument, got %d", manyMessage: "index expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.index() takes no keyword arguments", anyKw: false},
	"bytes.isalnum":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isalnum() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isalnum() takes no keyword arguments", anyKw: false},
	"bytes.isalpha":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isalpha() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isalpha() takes no keyword arguments", anyKw: false},
	"bytes.isascii":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isascii() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isascii() takes no keyword arguments", anyKw: false},
	"bytes.isdigit":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isdigit() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isdigit() takes no keyword arguments", anyKw: false},
	"bytes.islower":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.islower() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.islower() takes no keyword arguments", anyKw: false},
	"bytes.isspace":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isspace() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isspace() takes no keyword arguments", anyKw: false},
	"bytes.istitle":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.istitle() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.istitle() takes no keyword arguments", anyKw: false},
	"bytes.isupper":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.isupper() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.isupper() takes no keyword arguments", anyKw: false},
	"bytes.join":         {minArgs: 1, maxArgs: 1, fewMessage: "bytes.join() takes exactly one argument (%d given)", manyMessage: "bytes.join() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.join() takes no keyword arguments", anyKw: false},
	"bytes.ljust":        {minArgs: 1, maxArgs: 2, fewMessage: "ljust expected at least 1 argument, got %d", manyMessage: "ljust expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.ljust() takes no keyword arguments", anyKw: false},
	"bytes.lower":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.lower() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.lower() takes no keyword arguments", anyKw: false},
	"bytes.lstrip":       {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "lstrip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "bytes.lstrip() takes no keyword arguments", anyKw: false},
	"bytes.maketrans":    {minArgs: 2, maxArgs: 2, fewMessage: "maketrans expected 2 arguments, got %d", manyMessage: "maketrans expected 2 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.maketrans() takes no keyword arguments", anyKw: false},
	"bytes.partition":    {minArgs: 1, maxArgs: 1, fewMessage: "bytes.partition() takes exactly one argument (%d given)", manyMessage: "bytes.partition() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.partition() takes no keyword arguments", anyKw: false},
	"bytes.removeprefix": {minArgs: 1, maxArgs: 1, fewMessage: "bytes.removeprefix() takes exactly one argument (%d given)", manyMessage: "bytes.removeprefix() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.removeprefix() takes no keyword arguments", anyKw: false},
	"bytes.removesuffix": {minArgs: 1, maxArgs: 1, fewMessage: "bytes.removesuffix() takes exactly one argument (%d given)", manyMessage: "bytes.removesuffix() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.removesuffix() takes no keyword arguments", anyKw: false},
	"bytes.replace":      {minArgs: 2, maxArgs: 3, fewMessage: "replace expected at least 2 arguments, got %d", manyMessage: "replace expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.replace() takes no keyword arguments", anyKw: false},
	"bytes.rfind":        {minArgs: 1, maxArgs: 3, fewMessage: "rfind expected at least 1 argument, got %d", manyMessage: "rfind expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.rfind() takes no keyword arguments", anyKw: false},
	"bytes.rindex":       {minArgs: 1, maxArgs: 3, fewMessage: "rindex expected at least 1 argument, got %d", manyMessage: "rindex expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.rindex() takes no keyword arguments", anyKw: false},
	"bytes.rjust":        {minArgs: 1, maxArgs: 2, fewMessage: "rjust expected at least 1 argument, got %d", manyMessage: "rjust expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.rjust() takes no keyword arguments", anyKw: false},
	"bytes.rpartition":   {minArgs: 1, maxArgs: 1, fewMessage: "bytes.rpartition() takes exactly one argument (%d given)", manyMessage: "bytes.rpartition() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.rpartition() takes no keyword arguments", anyKw: false},
	"bytes.rsplit":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "rsplit() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.rstrip":       {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "rstrip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "bytes.rstrip() takes no keyword arguments", anyKw: false},
	"bytes.split":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "split() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.splitlines":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "splitlines() got an unexpected keyword argument '%s'", anyKw: false},
	"bytes.startswith":   {minArgs: 1, maxArgs: 3, fewMessage: "startswith expected at least 1 argument, got %d", manyMessage: "startswith expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "bytes.startswith() takes no keyword arguments", anyKw: false},
	"bytes.strip":        {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "strip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "bytes.strip() takes no keyword arguments", anyKw: false},
	"bytes.swapcase":     {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.swapcase() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.swapcase() takes no keyword arguments", anyKw: false},
	"bytes.title":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.title() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.title() takes no keyword arguments", anyKw: false},
	"bytes.translate":    {minArgs: 1, maxArgs: 2, fewMessage: "translate() takes at least 1 positional argument (%d given)", manyMessage: "translate() takes at most 2 arguments (%d given)", kwNames: []string{"delete"}, kwMessage: "translate() takes at least 1 positional argument (0 given)", anyKw: false},
	"bytes.upper":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "bytes.upper() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.upper() takes no keyword arguments", anyKw: false},
	"bytes.zfill":        {minArgs: 1, maxArgs: 1, fewMessage: "bytes.zfill() takes exactly one argument (%d given)", manyMessage: "bytes.zfill() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "bytes.zfill() takes no keyword arguments", anyKw: false},
	"dict.clear":         {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.clear() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.clear() takes no keyword arguments", anyKw: false},
	"dict.copy":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.copy() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.copy() takes no keyword arguments", anyKw: false},
	"dict.fromkeys":      {minArgs: 1, maxArgs: 2, fewMessage: "fromkeys expected at least 1 argument, got %d", manyMessage: "fromkeys expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "dict.fromkeys() takes no keyword arguments", anyKw: false},
	"dict.get":           {minArgs: 1, maxArgs: 2, fewMessage: "get expected at least 1 argument, got %d", manyMessage: "get expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "dict.get() takes no keyword arguments", anyKw: false},
	"dict.items":         {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.items() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.items() takes no keyword arguments", anyKw: false},
	"dict.keys":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.keys() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.keys() takes no keyword arguments", anyKw: false},
	"dict.pop":           {minArgs: 1, maxArgs: 2, fewMessage: "pop expected at least 1 argument, got %d", manyMessage: "pop expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "dict.pop() takes no keyword arguments", anyKw: false},
	"dict.popitem":       {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.popitem() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.popitem() takes no keyword arguments", anyKw: false},
	"dict.setdefault":    {minArgs: 1, maxArgs: 2, fewMessage: "setdefault expected at least 1 argument, got %d", manyMessage: "setdefault expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "dict.setdefault() takes no keyword arguments", anyKw: false},
	"dict.update":        {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "update expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "", anyKw: true},
	"dict.values":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "dict.values() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "dict.values() takes no keyword arguments", anyKw: false},
	"list.append":        {minArgs: 1, maxArgs: 1, fewMessage: "list.append() takes exactly one argument (%d given)", manyMessage: "list.append() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "list.append() takes no keyword arguments", anyKw: false},
	"list.clear":         {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "list.clear() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "list.clear() takes no keyword arguments", anyKw: false},
	"list.copy":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "list.copy() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "list.copy() takes no keyword arguments", anyKw: false},
	"list.count":         {minArgs: 1, maxArgs: 1, fewMessage: "list.count() takes exactly one argument (%d given)", manyMessage: "list.count() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "list.count() takes no keyword arguments", anyKw: false},
	"list.extend":        {minArgs: 1, maxArgs: 1, fewMessage: "list.extend() takes exactly one argument (%d given)", manyMessage: "list.extend() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "list.extend() takes no keyword arguments", anyKw: false},
	"list.index":         {minArgs: 1, maxArgs: 3, fewMessage: "index expected at least 1 argument, got %d", manyMessage: "index expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "list.index() takes no keyword arguments", anyKw: false},
	"list.insert":        {minArgs: 2, maxArgs: 2, fewMessage: "insert expected 2 arguments, got %d", manyMessage: "insert expected 2 arguments, got %d", kwNames: []string{}, kwMessage: "list.insert() takes no keyword arguments", anyKw: false},
	"list.pop":           {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "pop expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "list.pop() takes no keyword arguments", anyKw: false},
	"list.remove":        {minArgs: 1, maxArgs: 1, fewMessage: "list.remove() takes exactly one argument (%d given)", manyMessage: "list.remove() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "list.remove() takes no keyword arguments", anyKw: false},
	"list.reverse":       {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "list.reverse() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "list.reverse() takes no keyword arguments", anyKw: false},
	"list.sort":          {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "sort() takes at most 2 arguments (%d given)", kwNames: []string{"key", "reverse"}, kwMessage: "sort() got an unexpected keyword argument '%s'", anyKw: false},
	"str.capitalize":     {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.capitalize() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.capitalize() takes no keyword arguments", anyKw: false},
	"str.casefold":       {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.casefold() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.casefold() takes no keyword arguments", anyKw: false},
	"str.center":         {minArgs: 1, maxArgs: 2, fewMessage: "center expected at least 1 argument, got %d", manyMessage: "center expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "str.center() takes no keyword arguments", anyKw: false},
	"str.count":          {minArgs: 1, maxArgs: 3, fewMessage: "count expected at least 1 argument, got %d", manyMessage: "count expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.count() takes no keyword arguments", anyKw: false},
	"str.encode":         {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "encode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "encode() got an unexpected keyword argument '%s'", anyKw: false},
	"str.endswith":       {minArgs: 1, maxArgs: 3, fewMessage: "endswith expected at least 1 argument, got %d", manyMessage: "endswith expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.endswith() takes no keyword arguments", anyKw: false},
	"str.expandtabs":     {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "expandtabs() got an unexpected keyword argument '%s'", anyKw: false},
	"str.find":           {minArgs: 1, maxArgs: 3, fewMessage: "find expected at least 1 argument, got %d", manyMessage: "find expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.find() takes no keyword arguments", anyKw: false},
	"str.format":         {minArgs: 0, maxArgs: -1, fewMessage: "", manyMessage: "", kwNames: []string{}, kwMessage: "", anyKw: true},
	"str.format_map":     {minArgs: 1, maxArgs: 1, fewMessage: "str.format_map() takes exactly one argument (%d given)", manyMessage: "str.format_map() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.format_map() takes no keyword arguments", anyKw: false},
	"str.index":          {minArgs: 1, maxArgs: 3, fewMessage: "index expected at least 1 argument, got %d", manyMessage: "index expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.index() takes no keyword arguments", anyKw: false},
	"str.isalnum":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isalnum() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isalnum() takes no keyword arguments", anyKw: false},
	"str.isalpha":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isalpha() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isalpha() takes no keyword arguments", anyKw: false},
	"str.isascii":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isascii() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isascii() takes no keyword arguments", anyKw: false},
	"str.isdecimal":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isdecimal() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isdecimal() takes no keyword arguments", anyKw: false},
	"str.isdigit":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isdigit() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isdigit() takes no keyword arguments", anyKw: false},
	"str.isidentifier":   {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isidentifier() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isidentifier() takes no keyword arguments", anyKw: false},
	"str.islower":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.islower() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.islower() takes no keyword arguments", anyKw: false},
	"str.isnumeric":      {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isnumeric() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isnumeric() takes no keyword arguments", anyKw: false},
	"str.isprintable":    {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isprintable() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isprintable() takes no keyword arguments", anyKw: false},
	"str.isspace":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isspace() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isspace() takes no keyword arguments", anyKw: false},
	"str.istitle":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.istitle() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.istitle() takes no keyword arguments", anyKw: false},
	"str.isupper":        {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.isupper() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.isupper() takes no keyword arguments", anyKw: false},
	"str.join":           {minArgs: 1, maxArgs: 1, fewMessage: "str.join() takes exactly one argument (%d given)", manyMessage: "str.join() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.join() takes no keyword arguments", anyKw: false},
	"str.ljust":          {minArgs: 1, maxArgs: 2, fewMessage: "ljust expected at least 1 argument, got %d", manyMessage: "ljust expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "str.ljust() takes no keyword arguments", anyKw: false},
	"str.lower":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.lower() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.lower() takes no keyword arguments", anyKw: false},
	"str.lstrip":         {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "lstrip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "str.lstrip() takes no keyword arguments", anyKw: false},
	"str.maketrans":      {minArgs: 1, maxArgs: 3, fewMessage: "maketrans expected at least 1 argument, got %d", manyMessage: "maketrans expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.maketrans() takes no keyword arguments", anyKw: false},
	"str.partition":      {minArgs: 1, maxArgs: 1, fewMessage: "str.partition() takes exactly one argument (%d given)", manyMessage: "str.partition() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.partition() takes no keyword arguments", anyKw: false},
	"str.removeprefix":   {minArgs: 1, maxArgs: 1, fewMessage: "str.removeprefix() takes exactly one argument (%d given)", manyMessage: "str.removeprefix() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.removeprefix() takes no keyword arguments", anyKw: false},
	"str.removesuffix":   {minArgs: 1, maxArgs: 1, fewMessage: "str.removesuffix() takes exactly one argument (%d given)", manyMessage: "str.removesuffix() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.removesuffix() takes no keyword arguments", anyKw: false},
	"str.replace":        {minArgs: 2, maxArgs: 3, fewMessage: "replace() takes at least 2 positional arguments (%d given)", manyMessage: "replace() takes at most 3 arguments (%d given)", kwNames: []string{"count"}, kwMessage: "replace() takes at least 2 positional arguments (0 given)", anyKw: false},
	"str.rfind":          {minArgs: 1, maxArgs: 3, fewMessage: "rfind expected at least 1 argument, got %d", manyMessage: "rfind expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.rfind() takes no keyword arguments", anyKw: false},
	"str.rindex":         {minArgs: 1, maxArgs: 3, fewMessage: "rindex expected at least 1 argument, got %d", manyMessage: "rindex expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.rindex() takes no keyword arguments", anyKw: false},
	"str.rjust":          {minArgs: 1, maxArgs: 2, fewMessage: "rjust expected at least 1 argument, got %d", manyMessage: "rjust expected at most 2 arguments, got %d", kwNames: []string{}, kwMessage: "str.rjust() takes no keyword arguments", anyKw: false},
	"str.rpartition":     {minArgs: 1, maxArgs: 1, fewMessage: "str.rpartition() takes exactly one argument (%d given)", manyMessage: "str.rpartition() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.rpartition() takes no keyword arguments", anyKw: false},
	"str.rsplit":         {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "rsplit() got an unexpected keyword argument '%s'", anyKw: false},
	"str.rstrip":         {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "rstrip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "str.rstrip() takes no keyword arguments", anyKw: false},
	"str.split":          {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "split() got an unexpected keyword argument '%s'", anyKw: false},
	"str.splitlines":     {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "splitlines() got an unexpected keyword argument '%s'", anyKw: false},
	"str.startswith":     {minArgs: 1, maxArgs: 3, fewMessage: "startswith expected at least 1 argument, got %d", manyMessage: "startswith expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.startswith() takes no keyword arguments", anyKw: false},
	"str.strip":          {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "strip expected at most 1 argument, got %d", kwNames: []string{}, kwMessage: "str.strip() takes no keyword arguments", anyKw: false},
	"str.swapcase":       {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.swapcase() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.swapcase() takes no keyword arguments", anyKw: false},
	"str.title":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.title() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.title() takes no keyword arguments", anyKw: false},
	"str.translate":      {minArgs: 1, maxArgs: 1, fewMessage: "str.translate() takes exactly one argument (%d given)", manyMessage: "str.translate() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.translate() takes no keyword arguments", anyKw: false},
	"str.upper":          {minArgs: 0, maxArgs: 0, fewMessage: "", manyMessage: "str.upper() takes no arguments (%d given)", kwNames: []string{}, kwMessage: "str.upper() takes no keyword arguments", anyKw: false},
	"str.zfill":          {minArgs: 1, maxArgs: 1, fewMessage: "str.zfill() takes exactly one argument (%d given)", manyMessage: "str.zfill() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "str.zfill() takes no keyword arguments", anyKw: false},
	"tuple.count":        {minArgs: 1, maxArgs: 1, fewMessage: "tuple.count() takes exactly one argument (%d given)", manyMessage: "tuple.count() takes exactly one argument (%d given)", kwNames: []string{}, kwMessage: "tuple.count() takes no keyword arguments", anyKw: false},
	"tuple.index":        {minArgs: 1, maxArgs: 3, fewMessage: "index expected at least 1 argument, got %d", manyMessage: "index expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "tuple.index() takes no keyword arguments", anyKw: false},
}
