// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_arity_matrix.py. DO NOT EDIT.

package gojja2

import "github.com/mgilbir/gojja2/value"

// methodArityOlder is what an older CPython said about a call that does not fit
// a built-in method's signature.
//
// method_arity.go carries the default interpreter's wording in full; this
// carries only the entries an older one words differently, because most of them
// are identical and a second full copy per version would be four tables to keep
// in step. A method absent here answers as the default does.
// 3.13 is absent because it words every entry exactly as the default does: a
// block recording no difference is a line that can only rot.
var methodArityOlder = map[value.PythonVersion]map[string]methodSignature{
	// CPython 3.11: 27 of the table's entries differ.
	value.Python311: {
		"bytes.count":      {minArgs: 1, maxArgs: 3, fewMessage: "count() takes at least 1 argument (%d given)", manyMessage: "count() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.count() takes no keyword arguments", anyKw: false},
		"bytes.decode":     {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "decode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "'%s' is an invalid keyword argument for decode()", anyKw: false},
		"bytes.endswith":   {minArgs: 1, maxArgs: 3, fewMessage: "endswith() takes at least 1 argument (%d given)", manyMessage: "endswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.endswith() takes no keyword arguments", anyKw: false},
		"bytes.expandtabs": {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "'%s' is an invalid keyword argument for expandtabs()", anyKw: false},
		"bytes.find":       {minArgs: 1, maxArgs: 3, fewMessage: "find() takes at least 1 argument (%d given)", manyMessage: "find() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.find() takes no keyword arguments", anyKw: false},
		"bytes.hex":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "hex() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "bytes_per_sep"}, kwMessage: "'%s' is an invalid keyword argument for hex()", anyKw: false},
		"bytes.index":      {minArgs: 1, maxArgs: 3, fewMessage: "index() takes at least 1 argument (%d given)", manyMessage: "index() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.index() takes no keyword arguments", anyKw: false},
		"bytes.rfind":      {minArgs: 1, maxArgs: 3, fewMessage: "rfind() takes at least 1 argument (%d given)", manyMessage: "rfind() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.rfind() takes no keyword arguments", anyKw: false},
		"bytes.rindex":     {minArgs: 1, maxArgs: 3, fewMessage: "rindex() takes at least 1 argument (%d given)", manyMessage: "rindex() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.rindex() takes no keyword arguments", anyKw: false},
		"bytes.rsplit":     {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for rsplit()", anyKw: false},
		"bytes.split":      {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for split()", anyKw: false},
		"bytes.splitlines": {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "'%s' is an invalid keyword argument for splitlines()", anyKw: false},
		"bytes.startswith": {minArgs: 1, maxArgs: 3, fewMessage: "startswith() takes at least 1 argument (%d given)", manyMessage: "startswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.startswith() takes no keyword arguments", anyKw: false},
		"list.sort":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "sort() takes at most 2 arguments (%d given)", kwNames: []string{"key", "reverse"}, kwMessage: "'%s' is an invalid keyword argument for sort()", anyKw: false},
		"str.count":        {minArgs: 1, maxArgs: 3, fewMessage: "count() takes at least 1 argument (%d given)", manyMessage: "count() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.count() takes no keyword arguments", anyKw: false},
		"str.encode":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "encode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "'%s' is an invalid keyword argument for encode()", anyKw: false},
		"str.endswith":     {minArgs: 1, maxArgs: 3, fewMessage: "endswith() takes at least 1 argument (%d given)", manyMessage: "endswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.endswith() takes no keyword arguments", anyKw: false},
		"str.expandtabs":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "'%s' is an invalid keyword argument for expandtabs()", anyKw: false},
		"str.find":         {minArgs: 1, maxArgs: 3, fewMessage: "find() takes at least 1 argument (%d given)", manyMessage: "find() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.find() takes no keyword arguments", anyKw: false},
		"str.index":        {minArgs: 1, maxArgs: 3, fewMessage: "index() takes at least 1 argument (%d given)", manyMessage: "index() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.index() takes no keyword arguments", anyKw: false},
		"str.replace":      {minArgs: 2, maxArgs: 3, fewMessage: "replace expected at least 2 arguments, got %d", manyMessage: "replace expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.replace() takes no keyword arguments", anyKw: false},
		"str.rfind":        {minArgs: 1, maxArgs: 3, fewMessage: "rfind() takes at least 1 argument (%d given)", manyMessage: "rfind() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.rfind() takes no keyword arguments", anyKw: false},
		"str.rindex":       {minArgs: 1, maxArgs: 3, fewMessage: "rindex() takes at least 1 argument (%d given)", manyMessage: "rindex() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.rindex() takes no keyword arguments", anyKw: false},
		"str.rsplit":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for rsplit()", anyKw: false},
		"str.split":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for split()", anyKw: false},
		"str.splitlines":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "'%s' is an invalid keyword argument for splitlines()", anyKw: false},
		"str.startswith":   {minArgs: 1, maxArgs: 3, fewMessage: "startswith() takes at least 1 argument (%d given)", manyMessage: "startswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.startswith() takes no keyword arguments", anyKw: false},
	},
	// CPython 3.12: 27 of the table's entries differ.
	value.Python312: {
		"bytes.count":      {minArgs: 1, maxArgs: 3, fewMessage: "count() takes at least 1 argument (%d given)", manyMessage: "count() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.count() takes no keyword arguments", anyKw: false},
		"bytes.decode":     {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "decode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "'%s' is an invalid keyword argument for decode()", anyKw: false},
		"bytes.endswith":   {minArgs: 1, maxArgs: 3, fewMessage: "endswith() takes at least 1 argument (%d given)", manyMessage: "endswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.endswith() takes no keyword arguments", anyKw: false},
		"bytes.expandtabs": {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "'%s' is an invalid keyword argument for expandtabs()", anyKw: false},
		"bytes.find":       {minArgs: 1, maxArgs: 3, fewMessage: "find() takes at least 1 argument (%d given)", manyMessage: "find() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.find() takes no keyword arguments", anyKw: false},
		"bytes.hex":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "hex() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "bytes_per_sep"}, kwMessage: "'%s' is an invalid keyword argument for hex()", anyKw: false},
		"bytes.index":      {minArgs: 1, maxArgs: 3, fewMessage: "index() takes at least 1 argument (%d given)", manyMessage: "index() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.index() takes no keyword arguments", anyKw: false},
		"bytes.rfind":      {minArgs: 1, maxArgs: 3, fewMessage: "rfind() takes at least 1 argument (%d given)", manyMessage: "rfind() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.rfind() takes no keyword arguments", anyKw: false},
		"bytes.rindex":     {minArgs: 1, maxArgs: 3, fewMessage: "rindex() takes at least 1 argument (%d given)", manyMessage: "rindex() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.rindex() takes no keyword arguments", anyKw: false},
		"bytes.rsplit":     {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for rsplit()", anyKw: false},
		"bytes.split":      {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for split()", anyKw: false},
		"bytes.splitlines": {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "'%s' is an invalid keyword argument for splitlines()", anyKw: false},
		"bytes.startswith": {minArgs: 1, maxArgs: 3, fewMessage: "startswith() takes at least 1 argument (%d given)", manyMessage: "startswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "bytes.startswith() takes no keyword arguments", anyKw: false},
		"list.sort":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "sort() takes at most 2 arguments (%d given)", kwNames: []string{"key", "reverse"}, kwMessage: "'%s' is an invalid keyword argument for sort()", anyKw: false},
		"str.count":        {minArgs: 1, maxArgs: 3, fewMessage: "count() takes at least 1 argument (%d given)", manyMessage: "count() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.count() takes no keyword arguments", anyKw: false},
		"str.encode":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "encode() takes at most 2 arguments (%d given)", kwNames: []string{"encoding", "errors"}, kwMessage: "'%s' is an invalid keyword argument for encode()", anyKw: false},
		"str.endswith":     {minArgs: 1, maxArgs: 3, fewMessage: "endswith() takes at least 1 argument (%d given)", manyMessage: "endswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.endswith() takes no keyword arguments", anyKw: false},
		"str.expandtabs":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "expandtabs() takes at most 1 argument (%d given)", kwNames: []string{"tabsize"}, kwMessage: "'%s' is an invalid keyword argument for expandtabs()", anyKw: false},
		"str.find":         {minArgs: 1, maxArgs: 3, fewMessage: "find() takes at least 1 argument (%d given)", manyMessage: "find() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.find() takes no keyword arguments", anyKw: false},
		"str.index":        {minArgs: 1, maxArgs: 3, fewMessage: "index() takes at least 1 argument (%d given)", manyMessage: "index() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.index() takes no keyword arguments", anyKw: false},
		"str.replace":      {minArgs: 2, maxArgs: 3, fewMessage: "replace expected at least 2 arguments, got %d", manyMessage: "replace expected at most 3 arguments, got %d", kwNames: []string{}, kwMessage: "str.replace() takes no keyword arguments", anyKw: false},
		"str.rfind":        {minArgs: 1, maxArgs: 3, fewMessage: "rfind() takes at least 1 argument (%d given)", manyMessage: "rfind() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.rfind() takes no keyword arguments", anyKw: false},
		"str.rindex":       {minArgs: 1, maxArgs: 3, fewMessage: "rindex() takes at least 1 argument (%d given)", manyMessage: "rindex() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.rindex() takes no keyword arguments", anyKw: false},
		"str.rsplit":       {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "rsplit() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for rsplit()", anyKw: false},
		"str.split":        {minArgs: 0, maxArgs: 2, fewMessage: "", manyMessage: "split() takes at most 2 arguments (%d given)", kwNames: []string{"sep", "maxsplit"}, kwMessage: "'%s' is an invalid keyword argument for split()", anyKw: false},
		"str.splitlines":   {minArgs: 0, maxArgs: 1, fewMessage: "", manyMessage: "splitlines() takes at most 1 argument (%d given)", kwNames: []string{"keepends"}, kwMessage: "'%s' is an invalid keyword argument for splitlines()", anyKw: false},
		"str.startswith":   {minArgs: 1, maxArgs: 3, fewMessage: "startswith() takes at least 1 argument (%d given)", manyMessage: "startswith() takes at most 3 arguments (%d given)", kwNames: []string{}, kwMessage: "str.startswith() takes no keyword arguments", anyKw: false},
	},
}
