// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

package gojja2

import (
	"os"
	"regexp"
	"testing"

	"github.com/mgilbir/gojja2/value"
)

// The same fact is written down in three places that cannot import each other:
// PYTHON_VERSION in the Makefile, which decides the interpreter every generator
// probes; value.DefaultPythonVersion, which decides what a caller who does not
// choose gets; and the header of each generated file, which records the
// interpreter that actually produced it.
//
// They have to agree. If the Makefile moves and the constant does not, gojja2
// renders as one interpreter against tables built from another -- and nothing
// fails, because the goldens were regenerated to match the tables. That is the
// quiet wrong answer this whole knob exists to prevent, so it is checked here
// rather than left to a reviewer noticing.
var (
	makePin   = regexp.MustCompile(`(?m)^PYTHON_VERSION\s*:=\s*(\S+)\s*$`)
	genHeader = regexp.MustCompile(`// Code generated by \S+ from CPython (\d+\.\d+)\.\d+`)
)

func TestDefaultVersionMatchesThePin(t *testing.T) {
	want := value.DefaultPythonVersion.String()

	mk, err := os.ReadFile("Makefile")
	if err != nil {
		t.Fatalf("read Makefile: %v", err)
	}
	m := makePin.FindSubmatch(mk)
	if m == nil {
		t.Fatal("PYTHON_VERSION is not set in the Makefile; the generators have no pin")
	}
	if got := string(m[1]); got != want {
		t.Errorf("Makefile pins CPython %s but value.DefaultPythonVersion is %s.\n"+
			"A bump has to move both: the tables come from the pin and the constant "+
			"decides which interpreter a caller is promised.", got, want)
	}

	// Every generated file that names its interpreter has to name that one too,
	// or the committed tables are somebody else's answers.
	for _, f := range []string{
		"method_arity.go", "entities.go", "strclass.go", "casemap.go",
	} {
		src, err := os.ReadFile(f)
		if err != nil {
			t.Errorf("read %s: %v", f, err)
			continue
		}
		h := genHeader.FindSubmatch(src)
		if h == nil {
			t.Errorf("%s does not record which CPython generated it", f)
			continue
		}
		if got := string(h[1]); got != want {
			t.Errorf("%s was generated from CPython %s, but the default is %s; "+
				"run `make oracle`", f, got, want)
		}
	}
}

// Every version gojja2 claims to reproduce must be one it can name and accept.
// A constant added without a String case reports "unknown" in an error message,
// which is how a caller ends up unable to tell which interpreter refused them.
func TestEveryKnownVersionIsNamed(t *testing.T) {
	for v := value.Python311; v <= value.Python314; v++ {
		if !v.Known() {
			continue
		}
		if v.String() == "unknown" {
			t.Errorf("PythonVersion(%d) is Known but has no String case", int(v))
		}
		if _, err := New(WithPythonVersion(v)); err != nil {
			t.Errorf("WithPythonVersion(%s) is Known but refused: %v", v, err)
		}
	}
	if !value.DefaultPythonVersion.Known() {
		t.Errorf("the default version %s is not Known", value.DefaultPythonVersion)
	}
}
