// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

package gojja2

import (
	"github.com/mgilbir/gojja2/errs"
	"github.com/mgilbir/gojja2/value"
)

// setMethods are set's seventeen methods.
//
// A template reaches a set through `d.keys() - xs` and nothing else, and the
// type carried a note saying its methods were therefore unreachable. They are
// not: `{% set s = d.keys() - xs %}{{ s.add(1) }}` is a method call on a set,
// and every one of them answered "'set object' has no attribute".
//
// Two rules run through the table, and they are CPython's rather than
// conveniences:
//
//   - a *method* takes any iterable, where an *operator* takes a set. So
//     `s.difference(['b'])` is a set and `s - ['b']` is a TypeError, and
//     `s.union(d)` unions with the dict's keys.
//   - the elements are hashed as they are taken, so an unhashable one refuses
//     from wherever it is met -- `s.union([[1]])` is "unhashable type: 'list'".
//
// The arity and its wording come from method_arity.go, which is generated by
// probing CPython, so "takes exactly one argument (2 given)" and "takes no
// arguments (1 given)" are its words and not a guess.
var setMethods = map[string]func(*State, value.Value, *value.CallArgs) (value.Value, error){
	"union":                       setCombine(setUnion, setArgumentOf),
	"intersection":                setCombine(setIntersect, setIntersectionArgument),
	"difference":                  setCombine(setSubtract, setArgumentOf),
	"symmetric_difference":        setCombine(setSymmetric, setArgumentOf),
	"update":                      setCombineInPlace(setUnion, setArgumentOf),
	"intersection_update":         setCombineInPlace(setIntersect, setIntersectionArgument),
	"difference_update":           setCombineInPlace(setSubtract, setArgumentOf),
	"symmetric_difference_update": setCombineInPlace(setSymmetric, setArgumentOf),
	"issubset":                    setRelation(false),
	"issuperset":                  setRelation(true),
	"isdisjoint":                  methodSetIsdisjoint,
	"add":                         methodSetAdd,
	"remove":                      methodSetRemove,
	"discard":                     methodSetDiscard,
	"pop":                         methodSetPop,
	"clear":                       methodSetClear,
	"copy":                        methodSetCopy,
}

// setOf unwraps the receiver, which the caller has already bound.
func setOf(r value.Value) (*value.Set, bool) {
	s, ok := r.Interface().(*value.Set)
	return s, ok
}

// setArgument reads an argument as a set, which is what every method that takes
// one does: any iterable, hashed as it goes.
//
// Not iterable is reported first and hashing second, which is the order CPython
// reaches them in -- `s.union(1)` is "'int' object is not iterable" and
// `s.union([[1]])` is "unhashable type: 'list'". The walk is charged a step per
// element, like every other one that reads a caller's sequence.
func setArgument(st *State, v value.Value) (*value.Set, error) {
	seq, err := value.Iterate(v)
	if err != nil {
		return nil, err
	}
	var items []value.Value
	for item := range seq {
		if err := st.Step(1); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return value.NewSet(items, st.PythonVersion(), st)
}

// setArgumentReader reads one argument of a combining method, given the set it
// is being combined with.
type setArgumentReader func(st *State, v value.Value, have *value.Set) (*value.Set, error)

// setArgumentOf reads the whole argument, hashing every element.
func setArgumentOf(st *State, v value.Value, _ *value.Set) (*value.Set, error) {
	return setArgument(st, v)
}

// setIntersectionArgument reads what an intersection needs of its argument.
//
// set_intersection walks an argument that is not itself a set one element at a
// time and stops as soon as the result holds every member of the receiver --
// nothing after that can add to it -- so an element after that point is never
// hashed: `{'b', 'c'}.intersection(['b', 'c', [1]])` is the set, not "unhashable
// type: 'list'". The check follows an element that was found, not each element,
// so an empty receiver reads the whole argument. intersection_update is written
// over the same call, in every version; issubset is from 3.12, before which it
// built the whole set first.
//
// What is returned holds only the members of have that were found, which is all
// an intersection and a subset test read of it.
func setIntersectionArgument(st *State, v value.Value, have *value.Set) (*value.Set, error) {
	if _, isSet := v.Interface().(*value.Set); isSet {
		return setArgument(st, v)
	}
	seq, err := value.Iterate(v)
	if err != nil {
		return nil, err
	}
	found, err := value.NewSet(nil, st.PythonVersion(), st)
	if err != nil {
		return nil, err
	}
	for item := range seq {
		if err := st.Step(1); err != nil {
			return nil, err
		}
		if err := value.CheckHashable(item, st.PythonVersion(), value.AsPlainHash); err != nil {
			return nil, err
		}
		if !have.Has(item) {
			continue
		}
		if err := found.Add(item, st.PythonVersion(), st); err != nil {
			return nil, err
		}
		if found.Len() == have.Len() {
			break
		}
	}
	return found, nil
}

// setScan asks, for each element of an iterable in turn, whether the set holds
// it, and stops at the first whose answer is wantFound. isdisjoint and
// issuperset are written this way in CPython for an argument that is not a
// set: they never build one, so an element after the deciding one is not even
// hashed and `s.issuperset(['missing', [1]])` is False, not "unhashable type".
func setScan(st *State, s *value.Set, arg value.Value, wantFound bool) (bool, error) {
	seq, err := value.Iterate(arg)
	if err != nil {
		return false, err
	}
	for item := range seq {
		if err := st.Step(1); err != nil {
			return false, err
		}
		if err := value.CheckHashable(item, st.PythonVersion(), value.AsSetElement); err != nil {
			return false, err
		}
		if s.Has(item) == wantFound {
			return true, nil
		}
	}
	return false, nil
}

// setUnion, setIntersect, setSubtract and setSymmetric are the four
// combinations, each over the receiver's elements and one argument's.
func setUnion(have, add *value.Set) []value.Value {
	return append(append([]value.Value{}, have.Elements()...), add.Elements()...)
}

// The result is built from the *receiver's* elements wherever both hold one, so
// it keeps the receiver's member rather than the argument's equal-but-distinct
// one -- which is what CPython does, and what `1` meeting `True` shows.
func setIntersect(have, with *value.Set) []value.Value {
	var out []value.Value
	for _, v := range have.Elements() {
		if with.Has(v) {
			out = append(out, v)
		}
	}
	return out
}

func setSubtract(have, without *value.Set) []value.Value {
	var out []value.Value
	for _, v := range have.Elements() {
		if !without.Has(v) {
			out = append(out, v)
		}
	}
	return out
}

func setSymmetric(have, other *value.Set) []value.Value {
	out := setSubtract(have, other)
	for _, v := range other.Elements() {
		if !have.Has(v) {
			out = append(out, v)
		}
	}
	return out
}

// setCombine builds a new set: union, intersection and difference take any
// number of arguments and fold left, symmetric_difference takes exactly one.
// The arity table is what enforces the difference.
func setCombine(fold func(have, with *value.Set) []value.Value, read setArgumentReader) func(*State, value.Value, *value.CallArgs) (value.Value, error) {
	return func(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
		acc, ok := setOf(r)
		if !ok {
			return value.Undefined, nil
		}
		for _, arg := range a.Pos {
			with, err := read(st, arg, acc)
			if err != nil {
				return value.Undefined, err
			}
			next, err := value.NewSet(fold(acc, with), st.PythonVersion(), st)
			if err != nil {
				return value.Undefined, err
			}
			acc = next
		}
		if acc == r.Interface() {
			// No arguments at all, so the answer is a copy: `s.union()`
			// is a new set, not the receiver, which shows the moment
			// anything mutates either one.
			out, err := value.NewSet(acc.Elements(), st.PythonVersion(), st)
			if err != nil {
				return value.Undefined, err
			}
			acc = out
		}
		return value.FromObject(acc), nil
	}
}

// setCombineInPlace is setCombine landing back in the receiver and answering
// None, which is what every mutating method in Python answers.
func setCombineInPlace(fold func(have, with *value.Set) []value.Value, read setArgumentReader) func(*State, value.Value, *value.CallArgs) (value.Value, error) {
	return func(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
		s, ok := setOf(r)
		if !ok {
			return value.Undefined, nil
		}
		// Every argument is read and hashed before anything is written,
		// so a refusal leaves the set as it was.
		folded := s
		for _, arg := range a.Pos {
			with, err := read(st, arg, folded)
			if err != nil {
				return value.Undefined, err
			}
			next, err := value.NewSet(fold(folded, with), st.PythonVersion(), st)
			if err != nil {
				return value.Undefined, err
			}
			folded = next
		}
		if folded != s {
			if err := s.Reset(folded.Elements(), st.PythonVersion(), st); err != nil {
				return value.Undefined, err
			}
		}
		return value.None, nil
	}
}

// setRelation is issubset and issuperset, which compare against any iterable
// rather than only a set.
func setRelation(superset bool) func(*State, value.Value, *value.CallArgs) (value.Value, error) {
	return func(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
		s, ok := setOf(r)
		if !ok {
			return value.Undefined, nil
		}
		if _, isSet := a.Pos[0].Interface().(*value.Set); superset && !isSet {
			missed, err := setScan(st, s, a.Pos[0], false)
			if err != nil {
				return value.Undefined, err
			}
			return value.Bool(!missed), nil
		}
		var other *value.Set
		var err error
		if superset || !st.PythonVersion().IssubsetStopsWhenFull() {
			other, err = setArgument(st, a.Pos[0])
		} else {
			other, err = setIntersectionArgument(st, a.Pos[0], s)
		}
		if err != nil {
			return value.Undefined, err
		}
		small, big := s, other
		if superset {
			small, big = other, s
		}
		for _, v := range small.Elements() {
			if !big.Has(v) {
				return value.False, nil
			}
		}
		return value.True, nil
	}
}

func methodSetIsdisjoint(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	if _, isSet := a.Pos[0].Interface().(*value.Set); !isSet {
		shared, err := setScan(st, s, a.Pos[0], true)
		if err != nil {
			return value.Undefined, err
		}
		return value.Bool(!shared), nil
	}
	other, err := setArgument(st, a.Pos[0])
	if err != nil {
		return value.Undefined, err
	}
	for _, v := range other.Elements() {
		if s.Has(v) {
			return value.False, nil
		}
	}
	return value.True, nil
}

func methodSetAdd(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	if err := s.Add(a.Pos[0], st.PythonVersion(), st); err != nil {
		return value.Undefined, err
	}
	return value.None, nil
}

// methodSetRemove is remove, which raises KeyError for an element that is not
// there -- and takes a *set* as the key, where add refuses one.
//
// CPython's set_remove catches the unhashable TypeError, makes a frozenset of
// the key and looks that up instead, so `s.remove(other_set)` is a KeyError
// naming the set rather than a complaint about hashing it. Nothing here builds
// a frozenset, so the lookup always misses -- which is the same answer, because
// no set this type holds can contain one.
func methodSetRemove(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	key := a.Pos[0]
	if _, isSet := key.Interface().(*value.Set); isSet {
		return value.Undefined, errs.New(errs.KeyError, "%s",
			value.ReprFor(key, st.PythonVersion()))
	}
	if err := value.CheckHashable(key, st.PythonVersion(), value.AsSetElement); err != nil {
		return value.Undefined, err
	}
	if !s.Discard(key) {
		return value.Undefined, errs.New(errs.KeyError, "%s",
			value.ReprFor(key, st.PythonVersion()))
	}
	return value.None, nil
}

// methodSetDiscard is remove without the complaint, and it takes a set the same
// way: set_discard shares set_remove's frozenset fallback.
func methodSetDiscard(st *State, r value.Value, a *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	key := a.Pos[0]
	if _, isSet := key.Interface().(*value.Set); isSet {
		return value.None, nil
	}
	if err := value.CheckHashable(key, st.PythonVersion(), value.AsSetElement); err != nil {
		return value.Undefined, err
	}
	s.Discard(key)
	return value.None, nil
}

// methodSetPop takes an arbitrary element, which for CPython is the first in
// its hash order and here the first in the order this set keeps. See
// docs/divergences.md: the two orders are the one thing about a set that cannot
// be reproduced, and this is where it is most visible.
func methodSetPop(st *State, r value.Value, _ *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	v, got := s.Pop()
	if !got {
		return value.Undefined, errs.New(errs.KeyError, "'pop from an empty set'")
	}
	return v, nil
}

func methodSetClear(st *State, r value.Value, _ *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	if err := s.Reset(nil, st.PythonVersion(), st); err != nil {
		return value.Undefined, err
	}
	return value.None, nil
}

func methodSetCopy(st *State, r value.Value, _ *value.CallArgs) (value.Value, error) {
	s, ok := setOf(r)
	if !ok {
		return value.Undefined, nil
	}
	out, err := value.NewSet(s.Elements(), st.PythonVersion(), st)
	if err != nil {
		return value.Undefined, err
	}
	return value.FromObject(out), nil
}
