// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/oracle/gen_utf8.py. DO NOT EDIT.

package gojja2

// utf8DecodeCases is how many byte sequences the digest covers: every one- and
// two-byte sequence, and every three- and four-byte sequence over the 30
// bytes a decision turns on.
const utf8DecodeCases = 902792

// utf8DecodeDigest is a sha256 over what CPython's UTF-8 decoder makes of each
// of those: the strict outcome -- the decoded text, or the exception's own
// message, reason and position range included -- and then what errors="replace"
// and errors="ignore" leave behind.
//
// The last two are not redundant. They are what pins the *size* of an error:
// the handler runs once per error rather than once per byte, so a decoder that
// splits one truncated sequence into two errors writes two replacement
// characters where CPython writes one, and no strict message would say so.
//
// Regenerate with `make utf8`. See the generator for how to find what moved.
const utf8DecodeDigest = "25b9fa308ec65877eec7ad8a62234f0493cab39a99e16549e97f496764ed1852"
