// Copyright 2026 The gojja2 Authors
// SPDX-License-Identifier: Apache-2.0

package conformance

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"

	"github.com/mgilbir/gojja2/value"
)

// Oracle is a live CPython jinja2, kept warm behind a pipe.
//
// The batch tool starts an interpreter per run, which costs about a tenth of a
// second and is irrelevant for a corpus of a thousand files. A differential
// fuzzer asks hundreds of thousands of questions, so it needs the interpreter
// to stay up: this drives tools/oracle/oracle_server.py over stdin and stdout,
// one JSON object per line.
type Oracle struct {
	cmd    *exec.Cmd
	stdin  io.WriteCloser
	stdout *bufio.Reader
	stderr *strings.Builder

	// mu serialises requests, because the server is a single interpreter
	// answering one line at a time.
	mu sync.Mutex
}

// OracleRequest is one render to perform.
type OracleRequest struct {
	Name      string            `json:"name,omitempty"`
	Source    string            `json:"src"`
	Context   json.RawMessage   `json:"ctx,omitempty"`
	Settings  map[string]any    `json:"settings,omitempty"`
	Templates map[string]string `json:"templates,omitempty"`
	// Profile names an environment profile; see profile.go.
	Profile string `json:"profile,omitempty"`
}

// OracleResult is what CPython jinja2 did with it.
type OracleResult struct {
	OK     bool         `json:"ok"`
	Output string       `json:"output"`
	Error  *GoldenError `json:"error"`
	// Resource is set when the render hit the server's time or memory
	// limit rather than failing on its own terms. Such a result says
	// nothing about conformance and is discarded.
	Resource bool `json:"resource"`
}

// OracleIdentity is which interpreter and libraries answered.
//
// It matters because it is the specification. CPython carries its own Unicode
// and words several errors its own way, so an oracle on a different release
// answers different questions: a differential run against one would report
// every version difference as a gojja2 bug, and a golden regenerated by one
// would quietly become some other interpreter's answer.
type OracleIdentity struct {
	Python     string `json:"python"`
	PythonFull string `json:"python_full"`
	Jinja2     string `json:"jinja2"`
	MarkupSafe string `json:"markupsafe"`
}

func (i OracleIdentity) String() string {
	return fmt.Sprintf("CPython %s, jinja2 %s, markupsafe %s",
		i.PythonFull, i.Jinja2, i.MarkupSafe)
}

// ExpectedOracle is the identity the committed goldens were recorded under.
//
// Every golden carries it, so the answer comes from the data being graded
// rather than from a constant that could drift away from it. The first golden
// in lexical order is read; oracle.py writes the same block into all of them.
func ExpectedOracle(root string) (*OracleIdentity, error) {
	dir := filepath.Join(root, "testdata", "golden")
	var first string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".json") {
			first = path
			return fs.SkipAll
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("conformance: reading %s: %w", dir, err)
	}
	if first == "" {
		return nil, fmt.Errorf("conformance: no goldens under %s", dir)
	}
	raw, err := os.ReadFile(first)
	if err != nil {
		return nil, err
	}
	var g Golden
	if err := json.Unmarshal(raw, &g); err != nil {
		return nil, fmt.Errorf("conformance: parsing %s: %w", first, err)
	}
	str := func(k string) string {
		v, _ := g.Oracle[k].(string)
		return v
	}
	full := str("python")
	minor := full
	if i := strings.IndexByte(full, '.'); i >= 0 {
		if j := strings.IndexByte(full[i+1:], '.'); j >= 0 {
			minor = full[:i+1+j]
		}
	}
	return &OracleIdentity{
		Python:     minor,
		PythonFull: full,
		Jinja2:     str("version"),
		MarkupSafe: str("markupsafe"),
	}, nil
}

// PythonVersionFor turns the minor version a sweep asked for into the setting
// gojja2 reproduces it with. "" is the pin.
//
// The two have to move together, which is why this lives beside the oracle
// rather than in the test: an oracle running 3.11 compared against a gojja2
// reproducing 3.13 would report every version-specific rule as a divergence,
// and every one of those reports would be about the harness.
func PythonVersionFor(version string) (value.PythonVersion, error) {
	switch version {
	case "":
		return value.DefaultPythonVersion, nil
	case "3.11":
		return value.Python311, nil
	case "3.12":
		return value.Python312, nil
	case "3.13":
		return value.Python313, nil
	case "3.14":
		return value.Python314, nil
	}
	return 0, fmt.Errorf("conformance: %q is not an interpreter gojja2 "+
		"reproduces; it knows 3.11, 3.12, 3.13 and 3.14", version)
}

// ErrMismatchedOracle reports that the live interpreter is not the one the
// committed goldens were recorded under. It is deliberately not ErrNoOracle:
// a missing oracle is a reason to skip, and a wrong one is a reason to stop.
var ErrMismatchedOracle = errors.New("conformance: the oracle is not the pinned interpreter")

// ErrNoOracle reports that no CPython jinja2 is available to ask.
var ErrNoOracle = errors.New("conformance: no CPython jinja2 oracle available (run `make venv`)")

// RepoRoot finds the module root by walking up from the working directory.
func RepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("conformance: go.mod not found above the working directory")
		}
		dir = parent
	}
}

// StartOracle launches the oracle server.
//
// It returns ErrNoOracle when the virtualenv is missing, so a test can skip
// rather than fail on a checkout that has not run `make venv`.
// StartOracle starts the pinned oracle: the interpreter the committed goldens
// were recorded under.
func StartOracle() (*Oracle, error) { return StartOracleFor("") }

// StartOracleFor starts the oracle under one of the interpreters gojja2
// reproduces, for a sweep that wants a version other than the pin. "" is the
// pin, and is what every ordinary caller wants.
//
// The version axis exists because the version-specific rules in
// value/pyversion.go were, until this, graded only by the corpus: a matrix of
// two-and-a-half thousand hand-written cases compared against pre-recorded
// goldens. The render differential generates sixty thousand templates and asked
// exactly one interpreter, so a rule that is wrong on 3.11 and right on 3.13
// could not be found at that scale. Three such rules were found by hand in one
// session; this is the sweep that would have found them.
//
// The identity check is not relaxed for this. It is pointed at the version that
// was asked for, so starting an oracle that is not the interpreter it claims to
// be is refused exactly as before.
func StartOracleFor(version string) (*Oracle, error) {
	root, err := RepoRoot()
	if err != nil {
		return nil, err
	}

	// GOJJA2_ORACLE_PYTHON overrides the interpreter, for a checkout whose
	// virtualenv lives elsewhere -- and, pointed at a path that does not
	// exist, for checking that the suite really does grade the committed
	// corpus with no Python, which is what the README promises.
	//
	// Whatever it names must be the pinned interpreter carrying the pinned
	// libraries: the goldens are that combination's answers, and any other is
	// a different specification. That used to be a sentence here asking the
	// caller to be careful; verifyIdentity below now checks it.
	python := os.Getenv("GOJJA2_ORACLE_PYTHON")
	if python == "" {
		python = filepath.Join(root, ".venv", "bin", "python")
	}
	script := filepath.Join(root, "tools", "oracle", "oracle_server.py")
	for _, path := range []string{python, script} {
		if _, err := os.Stat(path); err != nil {
			return nil, fmt.Errorf("%w: %s missing", ErrNoOracle, path)
		}
	}

	// uv builds the environment for a non-pinned interpreter per call, with
	// the pinned libraries, exactly as tools/oracle/pyversions.py does for
	// the golden matrix -- so a sweep reaches four interpreters without four
	// checked-in virtualenvs that could drift from the pin.
	cmd := exec.Command(python, script)
	if version != "" {
		want, err := ExpectedOracle(root)
		if err != nil {
			return nil, err
		}
		if version != want.Python {
			cmd = exec.Command("uv", "run", "--quiet",
				"--python", version, "--no-project",
				"--with", "jinja2=="+want.Jinja2,
				"--with", "markupsafe=="+want.MarkupSafe,
				"python", script)
		}
	}
	cmd.Dir = filepath.Join(root, "tools", "oracle")
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, err
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	stderr := &strings.Builder{}
	cmd.Stderr = stderr
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrNoOracle, err)
	}

	o := &Oracle{
		cmd:    cmd,
		stdin:  stdin,
		stdout: bufio.NewReaderSize(stdout, 1<<20),
		stderr: stderr,
	}
	// Prove the interpreter answers before any caller depends on it.
	if _, err := o.Render(OracleRequest{Source: "{{ 1 + 1 }}"}); err != nil {
		_ = o.Close()
		return nil, fmt.Errorf("%w: handshake failed: %v", ErrNoOracle, err)
	}
	// And prove it is the right one. GOJJA2_ORACLE_PYTHON accepts any
	// interpreter, and a .venv built by hand rather than by `make venv` can
	// hold anything too -- so "it answered" is not enough. Answering
	// *differently* is exactly what the other versions do.
	if err := o.verifyIdentity(root, version); err != nil {
		_ = o.Close()
		return nil, err
	}
	return o, nil
}

// exchange sends one request line and reads one reply line.
func (o *Oracle) exchange(req any) ([]byte, error) {
	line, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	o.mu.Lock()
	defer o.mu.Unlock()

	if _, err := o.stdin.Write(append(line, '\n')); err != nil {
		return nil, fmt.Errorf("oracle write: %w (stderr: %s)", err, o.stderr)
	}
	reply, err := o.stdout.ReadBytes('\n')
	if err != nil {
		return nil, fmt.Errorf("oracle read: %w (stderr: %s)", err, o.stderr)
	}
	return reply, nil
}

// verifyIdentity refuses an oracle that is not the one the goldens came from.
func (o *Oracle) verifyIdentity(root, version string) error {
	want, err := ExpectedOracle(root)
	if err != nil {
		return err
	}
	if version != "" {
		// A sweep asked for this one; the libraries are still the pin's,
		// because what a version sweep varies is the interpreter.
		want.Python, want.PythonFull = version, version
	}
	got, err := o.Hello()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNoOracle, err)
	}
	if got.Python != want.Python || got.Jinja2 != want.Jinja2 ||
		got.MarkupSafe != want.MarkupSafe {
		return fmt.Errorf("%w: it is %s, but the committed goldens were recorded "+
			"under CPython %s, jinja2 %s, markupsafe %s. Run `make venv`, or unset "+
			"GOJJA2_ORACLE_PYTHON",
			ErrMismatchedOracle, got, want.PythonFull, want.Jinja2, want.MarkupSafe)
	}
	return nil
}

// Render asks the oracle what CPython jinja2 makes of a template.
func (o *Oracle) Render(req OracleRequest) (*OracleResult, error) {
	reply, err := o.exchange(req)
	if err != nil {
		return nil, err
	}
	var result OracleResult
	if err := json.Unmarshal(reply, &result); err != nil {
		return nil, fmt.Errorf("oracle reply %q: %w", reply, err)
	}
	return &result, nil
}

// OracleAnalysis is what jinja2 makes of a template's structure: its tree and
// scope facts in gojja2's own vocabulary, and what it does with each of the
// caller's variables.
//
// Every field is a string of the same canonical form the engine produces, so a
// comparison is a byte comparison and there is nothing for two encoders to
// disagree about except the templates.
type OracleAnalysis struct {
	OK        bool              `json:"ok"`
	Tree      string            `json:"tree"`
	Info      string            `json:"info"`
	Variables map[string]string `json:"variables"`
	Error     *GoldenError      `json:"error"`
	// Resource is set when the analysis hit the server's time or memory
	// limit rather than failing on its own terms.
	Resource bool `json:"resource"`
}

// AnalyzeRequest asks what jinja2 makes of a template without rendering it.
type AnalyzeRequest struct {
	Analyze   bool              `json:"analyze"`
	Name      string            `json:"name,omitempty"`
	Source    string            `json:"src"`
	Settings  map[string]any    `json:"settings,omitempty"`
	Templates map[string]string `json:"templates,omitempty"`
	Profile   string            `json:"profile,omitempty"`
}

// Analyze asks the oracle for a template's structure and analyses.
//
// It is the render path's counterpart, and it exists for the same reason: a
// soak asks hundreds of thousands of questions, and starting an interpreter for
// each one is not a thing that can be done.
func (o *Oracle) Analyze(req AnalyzeRequest) (*OracleAnalysis, error) {
	req.Analyze = true
	reply, err := o.exchange(req)
	if err != nil {
		return nil, err
	}
	var out OracleAnalysis
	if err := json.Unmarshal(reply, &out); err != nil {
		return nil, fmt.Errorf("oracle analysis %q: %w", reply, err)
	}
	return &out, nil
}

// Hello asks the oracle which interpreter and libraries are answering.
func (o *Oracle) Hello() (*OracleIdentity, error) {
	reply, err := o.exchange(map[string]bool{"hello": true})
	if err != nil {
		return nil, err
	}
	var result struct {
		OK    bool            `json:"ok"`
		Hello *OracleIdentity `json:"hello"`
	}
	if err := json.Unmarshal(reply, &result); err != nil {
		return nil, fmt.Errorf("oracle hello %q: %w", reply, err)
	}
	if !result.OK || result.Hello == nil {
		return nil, fmt.Errorf("oracle did not say who it is: %q", reply)
	}
	return result.Hello, nil
}

// Close shuts the interpreter down.
func (o *Oracle) Close() error {
	_ = o.stdin.Close()
	return o.cmd.Wait()
}
